// html-react/src/pages/platform/Layout.tsx
import { Button, Form, Input, Layout, Menu, Modal, Typography, message } from 'antd'
import { Outlet, useLocation, useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useState } from 'react'
import { getPlatformAdmin } from '@/utils/platformRequest'
import { logoutPlatform, updatePlatformPassword } from '@/api/platform'
import { useUnhandledError } from '@/hooks/useUnhandledError'

const { Header, Sider, Content } = Layout

export default function PlatformLayout() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const location = useLocation()
  const admin = getPlatformAdmin()
  const isViewer = admin?.role === 'viewer'
  const showError = useUnhandledError()
  const [pwdOpen, setPwdOpen] = useState(false)
  const [saving, setSaving] = useState(false)
  const [form] = Form.useForm()

  const onLogout = async () => {
    await logoutPlatform()
    navigate('/platform/login', { replace: true })
  }

  const onSubmitPwd = async () => {
    try {
      const values = await form.validateFields()
      setSaving(true)
      await updatePlatformPassword(values)
      message.success(t('platform.password_updated'))
      setPwdOpen(false)
      form.resetFields()
    } catch (e) {
      if (e && typeof e === 'object' && 'errorFields' in e) return
      showError(e, t('platform.change_password'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Header
        style={{
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'space-between',
          background: '#0f172a',
          padding: '0 20px',
        }}
      >
        <Typography.Text strong style={{ color: '#fff', fontSize: 16 }}>
          {t('platform.title')}
        </Typography.Text>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <Typography.Text style={{ color: 'rgba(255,255,255,0.85)' }}>
            {admin?.name || admin?.username || ''}
          </Typography.Text>
          {isViewer ? (
            <Typography.Text style={{ color: '#cbd5e1', fontSize: 12 }}>
              {t('platform.role_viewer')}
            </Typography.Text>
          ) : null}
          <Button type="link" onClick={() => setPwdOpen(true)} style={{ color: '#93c5fd' }}>
            {t('platform.change_password')}
          </Button>
          <Button type="link" onClick={() => void onLogout()} style={{ color: '#93c5fd' }}>
            {t('header.logout')}
          </Button>
        </div>
      </Header>
      <Layout>
        <Sider width={200} theme="light">
          <Menu
            mode="inline"
            selectedKeys={[location.pathname]}
            items={[
              {
                key: '/platform/overview',
                label: t('menu.platform_overview'),
                onClick: () => navigate('/platform/overview'),
              },
              {
                key: '/platform/tenants',
                label: t('menu.tenant'),
                onClick: () => navigate('/platform/tenants'),
              },
              {
                key: '/platform/admins',
                label: t('menu.platform_admin'),
                onClick: () => navigate('/platform/admins'),
              },
              {
                key: '/platform/tenant-op-logs',
                label: t('menu.tenant_op_log'),
                onClick: () => navigate('/platform/tenant-op-logs'),
              },
              {
                key: '/platform/system-logs',
                label: t('menu.system_log'),
                onClick: () => navigate('/platform/system-logs'),
              },
              {
                key: '/platform/login-logs',
                label: t('menu.login_log'),
                onClick: () => navigate('/platform/login-logs'),
              },
              {
                key: '/platform/operation-logs',
                label: t('menu.operation_log'),
                onClick: () => navigate('/platform/operation-logs'),
              },
            ]}
          />
        </Sider>
        <Content style={{ padding: 16, background: '#f5f7fb' }}>
          <Outlet />
        </Content>
      </Layout>

      <Modal
        title={t('platform.change_password')}
        open={pwdOpen}
        onCancel={() => {
          setPwdOpen(false)
          form.resetFields()
        }}
        onOk={() => void onSubmitPwd()}
        confirmLoading={saving}
        destroyOnClose
      >
        <Form form={form} layout="vertical">
          <Form.Item
            name="old_password"
            label={t('platform.old_password')}
            rules={[{ required: true }]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item
            name="new_password"
            label={t('platform.new_password')}
            rules={[{ required: true, min: 6 }]}
          >
            <Input.Password />
          </Form.Item>
          <Form.Item
            name="confirm_password"
            label={t('platform.confirm_password')}
            dependencies={['new_password']}
            rules={[
              { required: true },
              ({ getFieldValue }) => ({
                validator(_, value) {
                  if (!value || getFieldValue('new_password') === value) return Promise.resolve()
                  return Promise.reject(new Error(t('platform.confirm_password')))
                },
              }),
            ]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      </Modal>
    </Layout>
  )
}

// html/src/views/platform/Layout.vue
<template>
  <div class="platform-layout">
    <header class="platform-header">
      <div class="brand">{{ $t('platform.title') }}</div>
      <div class="actions">
        <span class="admin-name">{{ adminName }}</span>
        <el-tag v-if="isViewer" size="small" type="info" effect="plain" class="role-tag">{{ $t('platform.role_viewer') }}</el-tag>
        <DarkModeSwitch class="platform-header-dark" />
        <LanguageSwitch class="platform-header-lang" />
        <el-button link type="primary" @click="pwdVisible = true">{{ $t('platform.change_password') }}</el-button>
        <el-button link type="primary" @click="onLogout">{{ $t('header.logout') }}</el-button>
      </div>
    </header>
    <div class="platform-body">
      <aside class="platform-aside">
        <el-menu :default-active="active" router>
          <el-menu-item index="/platform/overview">{{ $t('menu.platform_overview') }}</el-menu-item>
          <el-menu-item index="/platform/tenants">{{ $t('menu.tenant') }}</el-menu-item>
          <el-menu-item index="/platform/admins">{{ $t('menu.platform_admin') }}</el-menu-item>
          <el-menu-item index="/platform/tenant-op-logs">{{ $t('menu.tenant_op_log') }}</el-menu-item>
          <el-menu-item index="/platform/alert-deliveries">{{ $t('menu.platform_alert') }}</el-menu-item>
          <el-menu-item index="/platform/system-logs">{{ $t('menu.system_log') }}</el-menu-item>
          <el-menu-item index="/platform/login-logs">{{ $t('menu.login_log') }}</el-menu-item>
          <el-menu-item index="/platform/operation-logs">{{ $t('menu.operation_log') }}</el-menu-item>
        </el-menu>
      </aside>
      <main class="platform-main">
        <router-view />
      </main>
    </div>

    <el-dialog v-model="pwdVisible" :title="$t('platform.change_password')" width="420px" destroy-on-close @closed="resetPwd">
      <el-form ref="pwdFormRef" :model="pwdForm" :rules="pwdRules" label-width="100px">
        <el-form-item :label="$t('platform.old_password')" prop="old_password">
          <el-input v-model="pwdForm.old_password" type="password" show-password />
        </el-form-item>
        <el-form-item :label="$t('platform.new_password')" prop="new_password">
          <el-input v-model="pwdForm.new_password" type="password" show-password />
        </el-form-item>
        <el-form-item :label="$t('platform.confirm_password')" prop="confirm_password">
          <el-input v-model="pwdForm.confirm_password" type="password" show-password />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="pwdVisible = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="pwdSaving" @click="submitPwd">{{ $t('common.confirm') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { logoutPlatform, updatePlatformPassword } from '@/api/platform'
import { getPlatformAdmin } from '@/utils/platformRequest'
import DarkModeSwitch from '@/components/DarkModeSwitch.vue'
import LanguageSwitch from '@/components/LanguageSwitch.vue'

const { t } = useI18n()
const route = useRoute()
const router = useRouter()
const active = computed(() => route.path)
const platformAdmin = computed(() => getPlatformAdmin())
const adminName = computed(() => platformAdmin.value?.name || platformAdmin.value?.username || '')
const isViewer = computed(() => platformAdmin.value?.role === 'viewer')

const pwdVisible = ref(false)
const pwdSaving = ref(false)
const pwdFormRef = ref()
const pwdForm = reactive({
  old_password: '',
  new_password: '',
  confirm_password: '',
})
const pwdRules = {
  old_password: [{ required: true, message: () => t('platform.old_password'), trigger: 'blur' }],
  new_password: [
    { required: true, message: () => t('platform.new_password'), trigger: 'blur' },
    { min: 6, message: () => t('platform.new_password'), trigger: 'blur' },
  ],
  confirm_password: [
    { required: true, message: () => t('platform.confirm_password'), trigger: 'blur' },
    {
      validator: (_r, v, cb) => {
        if (v !== pwdForm.new_password) cb(new Error(t('platform.confirm_password')))
        else cb()
      },
      trigger: 'blur',
    },
  ],
}

const resetPwd = () => {
  pwdForm.old_password = ''
  pwdForm.new_password = ''
  pwdForm.confirm_password = ''
}

const submitPwd = async () => {
  await pwdFormRef.value?.validate()
  pwdSaving.value = true
  try {
    await updatePlatformPassword({ ...pwdForm })
    ElMessage.success(t('platform.password_updated'))
    pwdVisible.value = false
  } catch (e) {
    if (!e?.__handled) ElMessage.error(e?.message || t('common.operation_failed'))
  } finally {
    pwdSaving.value = false
  }
}

const onLogout = async () => {
  await logoutPlatform()
  router.replace('/platform/login')
}
</script>

<style scoped>
.platform-layout {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  background: var(--el-bg-color-page, #f5f7fb);
}
.platform-header {
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 0 20px;
  background: #0f172a;
  color: #fff;
}
.brand {
  font-weight: 600;
  letter-spacing: 0.02em;
}
.actions {
  display: flex;
  align-items: center;
  gap: 12px;
}
.admin-name {
  opacity: 0.85;
  font-size: 13px;
}
.role-tag {
  border-color: rgba(255, 255, 255, 0.35);
  color: #e2e8f0;
  background: transparent;
}
.platform-header-dark :deep(.dark-mode-switch) {
  color: rgba(255, 255, 255, 0.85);
  min-width: 36px;
  min-height: 36px;
  padding: 6px;
}
.platform-header-dark :deep(.dark-mode-switch:hover) {
  background-color: rgba(255, 255, 255, 0.1);
  color: #fff;
}
.platform-header-lang :deep(.language-switch) {
  color: rgba(255, 255, 255, 0.85);
  min-width: 36px;
  min-height: 36px;
  padding: 6px;
}
.platform-header-lang :deep(.language-switch:hover) {
  background-color: rgba(255, 255, 255, 0.1);
  color: #fff;
}
.platform-body {
  flex: 1;
  display: flex;
  min-height: 0;
}
.platform-aside {
  width: 200px;
  background: var(--el-bg-color, #fff);
  border-right: 1px solid var(--el-border-color-light, #e5e7eb);
}
.platform-main {
  flex: 1;
  padding: 16px;
  overflow: auto;
}
</style>
