// html-react/src/pages/admin/AdminList.tsx
import { useState } from 'react'
import { App, Button, Dropdown, Form, Input, Space, Switch, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import type { MenuProps } from 'antd'
import { DownOutlined, SettingOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  deleteAdmin,
  exportAdmin,
  getAdminList,
  kickOutUser,
  resetAdminGoogleAuth,
  resetPassword,
  unbindAdminGoogleAuth,
  updateAdmin,
} from '@/api/admin'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useColumnSetting } from '@/hooks/useColumnSetting'
import { promptSensitiveConfirm } from '@/utils/sensitiveConfirm'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import ColumnSettingDialog from '@/components/ColumnSettingDialog'
import AdminFormModal from './AdminFormModal'
import {
  adminInitialSearchForm,
  adminProtectedIds,
  getAdminDeptName,
  getAdminPositionName,
  getAdminRoleNames,
  transformAdminRow,
  type AdminRow,
} from './admin.config'

export default function AdminList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [formOpen, setFormOpen] = useState(false)
  const [editId, setEditId] = useState<string | number | null>(null)
  const [exporting, setExporting] = useState(false)
  const [pwdForm] = Form.useForm()

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<AdminRow, typeof adminInitialSearchForm>({
    fetchApi: getAdminList,
    initialSearchForm: adminInitialSearchForm,
    defaultSort: 'id:desc',
    normalizeRows: true,
    transformData: transformAdminRow,
  })

  const { toolbar, confirmDelete } = useCrudActions({
    createPermission: 'admin.store',
    onRefresh: refresh,
    onCreate: () => {
      setEditId(null)
      setFormOpen(true)
    },
    deleteApi: deleteAdmin,
  })

  const handleStatusChange = async (row: AdminRow, checked: boolean) => {
    if (adminProtectedIds.has(Number(row.id)) && !checked) {
      message.warning(t('admin.protected_cannot_disable', { defaultValue: '受保护账号不能禁用' }))
      return
    }
    try {
      await updateAdmin(row.id, { status: checked ? 1 : 0 })
      message.success(t('common.update_success'))
      await refresh()
    } catch (error) {
      showError(error, t('common.operation_failed'))
    }
  }

  const handleResetPassword = (row: AdminRow) => {
    pwdForm.resetFields()
    modal.confirm({
      title: t('admin.reset_password'),
      content: (
        <Form form={pwdForm} layout="vertical" style={{ marginTop: 16 }}>
          <Form.Item
            name="password"
            label={t('admin.new_password', { defaultValue: '新密码' })}
            rules={[{ required: true, message: t('admin.password_required') }]}
          >
            <Input.Password />
          </Form.Item>
        </Form>
      ),
      onOk: async () => {
        const values = await pwdForm.validateFields()
        void (async () => {
          try {
            const confirmCode = await promptSensitiveConfirm(modal, t)
            await resetPassword(row.id, {
              password: values.password,
              confirm_code: confirmCode,
            })
            message.success(t('admin.reset_password_success', { defaultValue: '密码已重置' }))
          } catch (error) {
            if ((error as Error)?.message === 'cancel') return
            showError(error, t('common.operation_failed'))
          }
        })()
      },
    })
  }

  const runConfirm = (title: string, content: string, action: () => Promise<void>) => {
    modal.confirm({
      title,
      content,
      onOk: async () => {
        try {
          await action()
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        }
      },
    })
  }

  const moreMenu = (row: AdminRow): MenuProps['items'] =>
    [
      getButtonState('admin.password').show
        ? {
            key: 'resetPassword',
            label: t('admin.reset_password'),
            onClick: () => handleResetPassword(row),
          }
        : null,
      getButtonState('admin.kick_out').show
        ? {
            key: 'kickOut',
            label: t('admin.kick_out', { defaultValue: '踢出登录' }),
            onClick: () =>
              runConfirm(
                t('admin.kick_out', { defaultValue: '踢出登录' }),
                t('admin.kick_out_confirm', {
                  username: row.username,
                  defaultValue: `确定踢出 ${row.username} 的全部登录吗？`,
                }),
                async () => {
                  await kickOutUser(row.id)
                  message.success(t('admin.kick_out_success', { defaultValue: '已踢出' }))
                },
              ),
          }
        : null,
      row.is_2fa_bound && getButtonState('admin.unbind_google_auth').show
        ? {
            key: 'unbind2fa',
            label: t('admin.unbind_google_auth', { defaultValue: '解绑谷歌验证' }),
            onClick: () =>
              runConfirm(
                t('admin.unbind_google_auth', { defaultValue: '解绑谷歌验证' }),
                t('admin.unbind_google_auth_confirm', {
                  defaultValue: '确定解绑该管理员的谷歌验证码吗？',
                }),
                async () => {
                  await unbindAdminGoogleAuth(row.id)
                  message.success(t('common.update_success'))
                  await refresh()
                },
              ),
          }
        : null,
      getButtonState('admin.reset_google_auth').show
        ? {
            key: 'reset2fa',
            label: t('admin.reset_google_auth', { defaultValue: '重置谷歌验证' }),
            onClick: () =>
              runConfirm(
                t('admin.reset_google_auth', { defaultValue: '重置谷歌验证' }),
                t('admin.reset_google_auth_confirm', {
                  defaultValue: '确定重置该管理员的谷歌验证码吗？',
                }),
                async () => {
                  await resetAdminGoogleAuth(row.id)
                  message.success(t('common.update_success'))
                  await refresh()
                },
              ),
          }
        : null,
    ].filter(Boolean) as MenuProps['items']

  const columns: ColumnsType<AdminRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('table.username'), dataIndex: 'username' },
    { title: t('table.nickname'), dataIndex: 'nickname' },
    { title: t('table.email'), dataIndex: 'email' },
    { title: t('table.department'), dataIndex: 'department', render: (_, row) => getAdminDeptName(row) },
    { title: t('table.position'), dataIndex: 'position', render: (_, row) => getAdminPositionName(row) },
    {
      title: t('table.roles'),
      dataIndex: 'roles',
      render: (_: AdminRow['roles'], row) => {
        const names = getAdminRoleNames(row)
        if (names === '-') return '-'
        return (
          <Space size={[4, 4]} wrap>
            {row.roles
              ?.map((role) => role.name)
              .filter(Boolean)
              .map((name) => (
                <Tag key={name}>{name}</Tag>
              ))}
          </Space>
        )
      },
    },
    {
      title: t('admin.google_auth_status', { defaultValue: '谷歌验证' }),
      dataIndex: 'is_2fa_bound',
      width: 110,
      render: (bound: boolean) =>
        bound
          ? t('admin.google_auth_bound', { defaultValue: '已绑定' })
          : t('admin.google_auth_not_bound', { defaultValue: '未绑定' }),
    },
    {
      title: t('table.status'),
      dataIndex: 'status',
      width: 100,
      render: (status: number, row) => (
        <Switch
          checked={status === 1}
          disabled={adminProtectedIds.has(Number(row.id)) || getButtonState('admin.update').disabled}
          onChange={(checked) => void handleStatusChange(row, checked)}
        />
      ),
    },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 220,
      fixed: 'end',
      render: (_, row) => (
        <Space>
          {getButtonState('admin.update').show && (
            <PermissionButton
              permission="admin.update"
              type="link"
              onClick={() => {
                setEditId(row.id)
                setFormOpen(true)
              }}
            >
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('admin.destroy').show && !adminProtectedIds.has(Number(row.id)) && (
            <PermissionButton
              permission="admin.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, row.username)}
            >
              {t('common.delete')}
            </PermissionButton>
          )}
          <Dropdown menu={{ items: moreMenu(row) }}>
            <a onClick={(e) => e.preventDefault()}>
              {t('common.more', { defaultValue: '更多' })} <DownOutlined />
            </a>
          </Dropdown>
        </Space>
      ),
    },
  ]

  const handleExport = async () => {
    setExporting(true)
    try {
      await exportAdmin(searchForm)
      message.success(t('common.queued', { defaultValue: '导出任务已提交，请稍后查看导出记录' }))
    } catch (error) {
      showError(error, t('common.operation_failed'))
    } finally {
      setExporting(false)
    }
  }

  const {
    filteredColumns,
    open: columnSettingOpen,
    openColumnSetting,
    closeColumnSetting,
    allColumns,
    visibleColumns,
    columnOrder,
    fixedColumns,
    handleConfirm: handleColumnSettingConfirm,
  } = useColumnSetting('admin', columns)

  return (
    <PageContainer
      title={t('menu.admin_management')}
      extra={
        <Space>
          {toolbar}
          <PermissionButton permission="admin.export" loading={exporting} onClick={() => void handleExport()}>
            {t('common.export', { defaultValue: '导出' })}
          </PermissionButton>
          <Button icon={<SettingOutlined />} onClick={openColumnSetting}>
            {t('common.column_setting')}
          </Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'username', label: t('table.username') },
          {
            name: 'status',
            label: t('table.status'),
            type: 'select',
            options: [
              { label: t('common.enabled'), value: 1 },
              { label: t('common.disabled'), value: 0 },
            ],
          },
          {
            name: 'is_2fa_bound',
            label: t('admin.google_auth_status', { defaultValue: '谷歌验证' }),
            type: 'select',
            options: [
              { label: t('admin.google_auth_bound', { defaultValue: '已绑定' }), value: '1' },
              { label: t('admin.google_auth_not_bound', { defaultValue: '未绑定' }), value: '0' },
            ],
          },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<AdminRow>
        rowKey="id"
        loading={loading}
        columns={filteredColumns}
        dataSource={tableData}
        scroll={{ x: 1400 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager, _f, sorter) =>
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }
      />
      <AdminFormModal
        open={formOpen}
        editId={editId}
        onClose={() => setFormOpen(false)}
        onSuccess={() => void refresh()}
      />
      <ColumnSettingDialog
        open={columnSettingOpen}
        onClose={closeColumnSetting}
        allColumns={allColumns}
        visibleColumns={visibleColumns}
        columnOrder={columnOrder}
        fixedColumns={fixedColumns}
        onConfirm={handleColumnSettingConfirm}
      />
    </PageContainer>
  )
}

// html/src/views/admin/AdminList.vue
<template>
  <ListPage
    ref="listPageRef"
    page-class="admin"
    :title="$t('menu.admin')"
    :add-button-text="$t('admin.add_admin')"
    :add-button-disabled="getButtonState('admin.store').disabled"
    :search-form="searchForm"
    :search-fields="searchFields"
    :initial-search-values="adminInitialSearchForm"
    i18n-prefix="admin"
    :table-data="tableData"
    :loading="loading"
    :table-columns="tableColumns"
    :table-key="`table-${tableColumns.length}`"
    :pagination="pagination"
    show-toolbar
    show-column-setting
    :visible-columns="visibleColumns"
    :all-columns="allColumns"
    :default-visible-columns="defaultVisibleColumns"
    :column-order="columnOrder"
    :fixed-columns="fixedColumns"
    :on-column-setting-confirm="handleColumnSettingConfirm"
    @add="handleAdd"
    @search="handleSearch"
    @reset="handleReset"
    @refresh="loadData"
    @page-change="loadData"
    @sort-change="handleSortChange"
  >
    <template #extra-buttons>
      <el-button
        type="success"
        :disabled="getButtonState('admin.export').disabled || isExporting"
        :loading="isExporting"
        @click="handleExport"
      >
        {{ $t('common.export') }}
      </el-button>
    </template>

    <template #status="{ row }">
      <el-switch
        :model-value="rowStatus(row) === 1"
        :disabled="isProtectedAdmin(row.id) || getButtonState('admin.update').disabled"
        @change="(val) => handleStatusChange(row, val)"
      />
    </template>

    <template #department="{ row }">
      {{ getDepartmentDisplayName(row.department) }}
    </template>

    <template #position="{ row }">
      {{ getPositionDisplayName(row.position) }}
    </template>

    <template #roles="{ row }">
      <template v-if="row.roles?.length">
        <el-tag
          v-for="role in getUniqueRoles(row.roles)"
          :key="role.id"
          style="margin-right: 5px; margin-bottom: 2px"
        >
          {{ role.name || role.Name }}
        </el-tag>
      </template>
      <span v-else>-</span>
    </template>

    <template #is_2fa_bound="{ row }">
      {{ row.is_2fa_bound ? $t('admin.google_auth_bound') : $t('admin.google_auth_not_bound') }}
    </template>

    <template #operation="{ row }">
      <TableActionButtons
        :row="row"
        :primary-actions="getPrimaryActions(row)"
        :more-actions="getMoreActions(row)"
        :get-button-state="getButtonState"
        @action="handleAction"
      />
    </template>

    <template #form>
      <AdminForm
        ref="adminFormRef"
        v-model="dialogVisible"
        :edit-id="editId"
        @success="handleFormSuccess"
      />
    </template>
  </ListPage>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useQueuedExport } from '@/composables/useQueuedExport'
import { ElMessage, ElMessageBox } from 'element-plus'
import ListPage from '@/components/ListPage.vue'
import TableActionButtons from '@/components/TableActionButtons.vue'
import AdminForm from './AdminForm.vue'
import { useStandardListPage } from '@/composables/useStandardListPage'
import { useColumnSetting } from '@/composables/useColumnSetting'
import { rowStatus } from '@/utils/listPageHelpers'
import { getField } from '@/utils/normalizeFormData'
import { getStatusOptions } from '@/utils/fieldOptions'
import {
  getAdminList,
  deleteAdmin,
  updateAdmin,
  exportAdmin,
  resetPassword,
  kickOutUser,
  unbindAdminGoogleAuth,
  resetAdminGoogleAuth
} from '@/api/admin'
import logger from '@/utils/logger'
import ErrorHandler from '@/utils/errorHandler'
import { promptSensitiveConfirm } from '@/utils/sensitiveConfirm'
import { compact, map as lodashMap } from 'lodash-es'
import {
  adminInitialSearchForm,
  createAdminSearchFields,
  createAdminTableColumns,
  isProtectedAdmin,
  getUniqueRoles,
  getDepartmentDisplayName,
  getPositionDisplayName
} from './admin.config'

const { t } = useI18n()
const listPageRef = ref(null)
const adminFormRef = ref(null)

const { isExporting, handleExport } = useQueuedExport({
  exportApi: exportAdmin,
  getParams: () => searchForm,
  requireExportId: false
})

const {
  pagination,
  tableData,
  loading,
  searchForm,
  dialogVisible,
  editId,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  handleAdd,
  handleDelete: handleDeleteRow,
  getButtonState
} = useStandardListPage({
  fetchApi: getAdminList,
  initialSearchForm: adminInitialSearchForm,
  defaultSort: 'id:desc',
  deleteApi: deleteAdmin,
  normalizeRows: false,
  tableRef: computed(() => listPageRef.value?.tableRef?.tableRef),
  beforeDelete: (row) => {
    if (isProtectedAdmin(row.id)) {
      ElMessage.warning(t('admin.protected_cannot_delete'))
      return false
    }
  }
})

const searchFields = computed(() => createAdminSearchFields(t, getStatusOptions))

const allTableColumns = computed(() => createAdminTableColumns(t))

const {
  tableColumns,
  visibleColumns,
  allColumns,
  defaultVisibleColumns,
  columnOrder,
  fixedColumns,
  handleColumnSettingConfirm
} = useColumnSetting('admin', allTableColumns, {
  adjacentPairs: [['department', 'position']]
})

const handleEdit = async (row) => {
  editId.value = row.id
  dialogVisible.value = true
  await new Promise((resolve) => setTimeout(resolve, 100))

  const uniqueRoleIds = row.roles
    ? [...new Set(compact(lodashMap(row.roles, (r) => r.id)))]
    : []

  adminFormRef.value?.setFormData({
    id: row.id,
    username: getField(row, 'username', ''),
    password: '',
    nickname: getField(row, 'nickname', ''),
    email: getField(row, 'email', ''),
    phone: getField(row, 'phone', ''),
    department_id: getField(row, 'department_id', null),
    position_id: getField(row, 'position_id', 0),
    role_ids: uniqueRoleIds,
    status: getField(row, 'status', 1),
    is_super_admin: row.is_super_admin === true
  })
}

const handleFormSuccess = () => {
  loadData()
}

const handleStatusChange = async (row, newStatus) => {
  if (isProtectedAdmin(row.id) && !newStatus) {
    ElMessage.warning(t('admin.protected_cannot_disable'))
    loadData()
    return
  }

  try {
    const statusValue = newStatus ? 1 : 0
    await updateAdmin(row.id, { status: statusValue })
    ElMessage.success(newStatus ? t('admin.enable_success') : t('admin.disable_success'))
    const admin = tableData.value.find((a) => a.id === row.id)
    if (admin) {
      admin.status = statusValue
    }
  } catch (error) {
    logger.error('Status change error:', error)
    loadData()
    if (!error.__handled) {
      ElMessage.error(error.response?.data?.message || error.message || t('common.operation_failed'))
    }
  }
}

const handleDelete = (row) => handleDeleteRow(row, loadData)

const handleResetPassword = async (row) => {
  try {
    const { value: password } = await ElMessageBox.prompt(
      t('admin.new_password'),
      t('admin.reset_password'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        inputType: 'password'
      }
    )
    const confirmCode = await promptSensitiveConfirm(t)
    await resetPassword(row.id, { password, confirm_code: confirmCode })
    ElMessage.success(t('admin.reset_password_success'))
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Reset password error:', error)
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

const handleKickOut = async (row) => {
  try {
    await ElMessageBox.confirm(
      t('admin.kick_out_confirm', { username: row.username }),
      t('form.tip'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning'
      }
    )
    await kickOutUser(row.id)
    ElMessage.success(t('admin.kick_out_success'))
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Kick out error:', error)
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

const getPrimaryActions = (row) => [
  {
    key: 'edit',
    label: t('common.edit'),
    type: 'primary',
    permission: 'admin.update',
    handler: handleEdit
  },
  {
    key: 'delete',
    label: t('common.delete'),
    type: 'danger',
    permission: 'admin.destroy',
    show: () => !isProtectedAdmin(row.id),
    handler: handleDelete
  }
]

const getMoreActions = (row) => [
  {
    key: 'resetPassword',
    command: 'resetPassword',
    label: t('admin.reset_password'),
    permission: 'admin.password',
    handler: handleResetPassword
  },
  {
    key: 'kickOut',
    command: 'kickOut',
    label: t('admin.kick_out'),
    permission: 'admin.kick_out',
    handler: handleKickOut
  },
  {
    key: 'unbindGoogleAuth',
    command: 'unbindGoogleAuth',
    label: t('admin.unbind_google_auth'),
    permission: 'admin.unbind_google_auth',
    divided: true,
    show: () => row.is_2fa_bound && !isProtectedAdmin(row.id),
    handler: handleUnbindGoogleAuth
  },
  {
    key: 'resetGoogleAuth',
    command: 'resetGoogleAuth',
    label: t('admin.reset_google_auth'),
    permission: 'admin.reset_google_auth',
    show: () => row.is_2fa_bound && !isProtectedAdmin(row.id),
    handler: handleResetGoogleAuth
  }
]

const handleAction = (command, row) => {
  switch (command) {
    case 'edit':
      handleEdit(row)
      break
    case 'delete':
      handleDelete(row)
      break
    case 'resetPassword':
      handleResetPassword(row)
      break
    case 'kickOut':
      handleKickOut(row)
      break
    case 'unbindGoogleAuth':
      handleUnbindGoogleAuth(row)
      break
    case 'resetGoogleAuth':
      handleResetGoogleAuth(row)
      break
  }
}

const handleUnbindGoogleAuth = async (row) => {
  try {
    const { value: code } = await ElMessageBox.prompt(
      t('admin.unbind_google_auth_confirm', { username: row.username }),
      t('admin.unbind_google_auth'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        inputPlaceholder: t('profile.enter_6_digit_code'),
        inputType: 'text',
        inputPattern: /^\d{6}$/,
        inputErrorMessage: t('profile.google_code_format')
      }
    )
    await unbindAdminGoogleAuth(row.id, { code })
    ElMessage.success(t('admin.unbind_google_auth_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Unbind google auth error:', error)
      if (!error?.__handled) {
        ElMessage.error(
          error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
        )
      }
    }
  }
}

const handleResetGoogleAuth = async (row) => {
  try {
    await ElMessageBox.confirm(
      t('admin.reset_google_auth_confirm', { username: row.username }),
      t('admin.reset_google_auth'),
      {
        confirmButtonText: t('common.confirm'),
        cancelButtonText: t('common.cancel'),
        type: 'warning'
      }
    )
    await resetAdminGoogleAuth(row.id)
    ElMessage.success(t('admin.reset_google_auth_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Reset google auth error:', error)
      if (!error?.__handled) {
        ElMessage.error(
          error.response?.data?.message || error.translatedMessage || error.message || t('common.operation_failed')
        )
      }
    }
  }
}
</script>
