// html/src/views/subscription/MySubscription.vue
<template>
  <div v-loading="loading" class="my-subscription">
    <h3 class="page-title">{{ $t('menu.subscription') }}</h3>

    <el-empty v-if="!loading && (!data || data.enabled === false)" :description="$t('subscription.not_available')" />

    <template v-else-if="data">
      <el-alert
        v-if="expiringSoon"
        class="block"
        type="warning"
        show-icon
        :closable="false"
        :title="remainingDays < 0 ? $t('subscription.expired_hint') : $t('subscription.expiring_hint', { days: remainingDays })"
      />

      <el-card shadow="never" class="block">
        <template #header>{{ $t('subscription.current_plan') }}</template>
        <el-descriptions :column="2" border size="small">
          <el-descriptions-item :label="$t('subscription.plan_name')">
            {{ data.plan?.name || '—' }}
            <code v-if="data.plan?.code" class="code">{{ data.plan.code }}</code>
          </el-descriptions-item>
          <el-descriptions-item :label="$t('subscription.status')">
            <el-tag v-if="sub?.status" size="small" :type="sub.status === 'active' ? 'success' : 'info'">{{ sub.status }}</el-tag>
            <span v-else>—</span>
          </el-descriptions-item>
          <el-descriptions-item :label="$t('subscription.starts_at')">{{ formatDate(sub?.starts_at) }}</el-descriptions-item>
          <el-descriptions-item :label="$t('subscription.ends_at')">
            {{ sub?.ends_at ? formatDate(sub.ends_at) : $t('subscription.no_expiry') }}
          </el-descriptions-item>
          <el-descriptions-item v-if="sub?.trial_ends_at" :label="$t('subscription.trial_ends_at')">
            {{ formatDate(sub.trial_ends_at) }}
          </el-descriptions-item>
          <el-descriptions-item v-if="data.plan?.description" :label="$t('subscription.description')" :span="2">
            {{ data.plan.description }}
          </el-descriptions-item>
        </el-descriptions>
        <p class="hint">{{ $t('subscription.upgrade_hint') }}</p>
      </el-card>

      <el-card v-if="limits.length" shadow="never" class="block">
        <template #header>{{ $t('subscription.quota_title') }}</template>
        <div v-for="l in limits" :key="l.key" class="quota-row">
          <div class="quota-head">
            <span>{{ l.name }}</span>
            <span class="muted">
              {{ l.unlimited ? $t('subscription.quota_unlimited', { used: l.used }) : $t('subscription.quota_usage', { used: l.used, limit: l.limit }) }}
            </span>
          </div>
          <el-progress
            v-if="!l.unlimited"
            :percentage="quotaPercent(l)"
            :status="quotaPercent(l) >= 100 ? 'exception' : quotaPercent(l) >= 80 ? 'warning' : undefined"
          />
        </div>
      </el-card>

      <el-card shadow="never" class="block">
        <template #header>{{ $t('subscription.features_title') }}</template>
        <el-table :data="features" row-key="key" size="small" border>
          <template #empty>{{ $t('subscription.features_empty') }}</template>
          <el-table-column prop="name" :label="$t('subscription.feature')" min-width="200" />
          <el-table-column :label="$t('subscription.kind')" width="120">
            <template #default="{ row }">
              <el-tag size="small" type="info">{{ kindLabel(row.kind) }}</el-tag>
            </template>
          </el-table-column>
          <el-table-column :label="$t('subscription.availability')" width="160">
            <template #default="{ row }">
              <el-tag v-if="row.enabled" size="small" type="success">{{ $t('subscription.enabled') }}</el-tag>
              <el-tag v-else size="small" type="warning">{{ $t('subscription.locked') }}</el-tag>
            </template>
          </el-table-column>
        </el-table>
      </el-card>
    </template>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { getMyPlan } from '@/api/subscription'

const { t } = useI18n()
const loading = ref(true)
const data = ref(null)

const features = computed(() => data.value?.features || [])
const limits = computed(() => data.value?.limits || [])
const sub = computed(() => data.value?.subscription || null)

const formatDate = (value) => {
  if (!value) return '—'
  const d = new Date(value)
  return Number.isNaN(d.getTime()) ? String(value) : d.toLocaleString()
}

const remainingDays = computed(() => {
  const end = sub.value?.ends_at ? new Date(sub.value.ends_at).getTime() : NaN
  if (Number.isNaN(end)) return null
  return Math.ceil((end - Date.now()) / 86400000)
})
const expiringSoon = computed(() => remainingDays.value !== null && remainingDays.value <= 7)

const quotaPercent = (l) => {
  if (l.unlimited) return 0
  // limit 0 (not unlimited) means no quota at all: show as full
  if (l.limit <= 0) return 100
  return Math.min(100, Math.round((l.used / l.limit) * 100))
}

const kindLabel = (kind) => {
  if (kind === 'capability') return t('subscription.kind_capability')
  if (kind === 'module') return t('subscription.kind_module')
  return t('subscription.kind_other')
}

onMounted(async () => {
  try {
    const res = await getMyPlan()
    data.value = res?.data || null
  } catch (e) {
    if (!e?.__handled) ElMessage.error(e?.message || t('common.operation_failed'))
  } finally {
    loading.value = false
  }
})
</script>

<style scoped>
.my-subscription {
  padding: 16px;
}
.page-title {
  margin: 0 0 16px;
}
.block {
  margin-bottom: 16px;
}
.code {
  margin-left: 8px;
  font-size: 12px;
}
.hint {
  margin: 12px 0 0;
  color: var(--el-text-color-secondary);
  font-size: 13px;
}
.quota-row {
  margin-bottom: 12px;
}
.quota-head {
  display: flex;
  gap: 12px;
  margin-bottom: 4px;
}
.muted {
  color: var(--el-text-color-secondary);
}
</style>

// html-react/src/pages/subscription/MySubscription.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Alert, Card, Descriptions, Empty, Progress, Space, Spin, Table, Tag, Typography } from 'antd'
import { useTranslation } from 'react-i18next'
import { getMyPlan, type MyPlanFeature, type MyPlanLimit, type MyPlanPayload } from '@/api/subscription'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'

function formatDate(value?: string | null): string {
  if (!value) return '—'
  const d = new Date(value)
  if (Number.isNaN(d.getTime())) return String(value)
  return d.toLocaleString()
}

function daysLeft(value?: string | null): number | null {
  if (!value) return null
  const end = new Date(value).getTime()
  if (Number.isNaN(end)) return null
  return Math.ceil((end - Date.now()) / 86400000)
}

export default function MySubscriptionPage() {
  const { t } = useTranslation()
  const showError = useUnhandledError()
  const [loading, setLoading] = useState(true)
  const [data, setData] = useState<MyPlanPayload | null>(null)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const res = await getMyPlan()
      setData((res?.data as MyPlanPayload) || null)
    } catch (e) {
      showError(e, t('common.operation_failed'))
    } finally {
      setLoading(false)
    }
  }, [showError, t])

  useEffect(() => {
    void load()
  }, [load])

  const features = useMemo(() => data?.features || [], [data])
  const limits = useMemo(() => data?.limits || [], [data])
  const sub = data?.subscription
  const remainingDays = daysLeft(sub?.ends_at)
  const expiringSoon = remainingDays !== null && remainingDays <= 7

  const kindLabel = (kind: MyPlanFeature['kind']) => {
    if (kind === 'capability') return t('subscription.kind_capability')
    if (kind === 'module') return t('subscription.kind_module')
    return t('subscription.kind_other')
  }

  if (loading && !data) {
    return (
      <PageContainer title={t('menu.subscription')}>
        <Spin />
      </PageContainer>
    )
  }

  if (!data || data.enabled === false) {
    return (
      <PageContainer title={t('menu.subscription')}>
        <Empty description={t('subscription.not_available')} />
      </PageContainer>
    )
  }

  return (
    <PageContainer title={t('menu.subscription')}>
      <Space direction="vertical" size="large" style={{ width: '100%' }}>
        {expiringSoon ? (
          <Alert
            type="warning"
            showIcon
            message={
              (remainingDays as number) < 0
                ? t('subscription.expired_hint')
                : t('subscription.expiring_hint', { days: remainingDays })
            }
          />
        ) : null}

        <Card title={t('subscription.current_plan')} loading={loading}>
          <Descriptions column={{ xs: 1, sm: 2 }} size="small">
            <Descriptions.Item label={t('subscription.plan_name')}>
              {data.plan?.name || '—'}
              {data.plan?.code ? (
                <Typography.Text code style={{ marginLeft: 8 }}>
                  {data.plan.code}
                </Typography.Text>
              ) : null}
            </Descriptions.Item>
            <Descriptions.Item label={t('subscription.status')}>
              {sub?.status ? <Tag color={sub.status === 'active' ? 'green' : 'default'}>{sub.status}</Tag> : '—'}
            </Descriptions.Item>
            <Descriptions.Item label={t('subscription.starts_at')}>{formatDate(sub?.starts_at)}</Descriptions.Item>
            <Descriptions.Item label={t('subscription.ends_at')}>
              {sub?.ends_at ? formatDate(sub.ends_at) : t('subscription.no_expiry')}
            </Descriptions.Item>
            {sub?.trial_ends_at ? (
              <Descriptions.Item label={t('subscription.trial_ends_at')}>{formatDate(sub.trial_ends_at)}</Descriptions.Item>
            ) : null}
            {data.plan?.description ? (
              <Descriptions.Item label={t('subscription.description')} span={2}>
                {data.plan.description}
              </Descriptions.Item>
            ) : null}
          </Descriptions>
          <Typography.Paragraph type="secondary" style={{ marginTop: 12, marginBottom: 0 }}>
            {t('subscription.upgrade_hint')}
          </Typography.Paragraph>
        </Card>

        {limits.length > 0 ? (
          <Card title={t('subscription.quota_title')} loading={loading}>
            <Space direction="vertical" size="middle" style={{ width: '100%' }}>
              {limits.map((l: MyPlanLimit) => {
                // limit 0 (not unlimited) means no quota at all: show as full
                const percent = l.unlimited ? 0 : l.limit <= 0 ? 100 : Math.min(100, Math.round((l.used / l.limit) * 100))
                return (
                  <div key={l.key}>
                    <Space style={{ marginBottom: 4 }}>
                      <span>{l.name}</span>
                      <Typography.Text type="secondary">
                        {l.unlimited
                          ? t('subscription.quota_unlimited', { used: l.used })
                          : t('subscription.quota_usage', { used: l.used, limit: l.limit })}
                      </Typography.Text>
                    </Space>
                    {l.unlimited ? null : (
                      <Progress percent={percent} status={percent >= 100 ? 'exception' : percent >= 80 ? 'active' : 'normal'} />
                    )}
                  </div>
                )
              })}
            </Space>
          </Card>
        ) : null}

        <Card title={t('subscription.features_title')} loading={loading}>
          <Table<MyPlanFeature>
            size="small"
            rowKey="key"
            pagination={false}
            dataSource={features}
            locale={{ emptyText: t('subscription.features_empty') }}
            columns={[
              { title: t('subscription.feature'), dataIndex: 'name' },
              {
                title: t('subscription.kind'),
                dataIndex: 'kind',
                width: 120,
                render: (v: MyPlanFeature['kind']) => <Tag>{kindLabel(v)}</Tag>,
              },
              {
                title: t('subscription.availability'),
                dataIndex: 'enabled',
                width: 160,
                render: (v: boolean) =>
                  v ? (
                    <Tag color="green">{t('subscription.enabled')}</Tag>
                  ) : (
                    <Tag color="orange">{t('subscription.locked')}</Tag>
                  ),
              },
            ]}
          />
        </Card>
      </Space>
    </PageContainer>
  )
}
