// html/src/views/platform/Entitlements.vue
<template>
  <div class="platform-entitlements">
    <el-card shadow="never" class="block">
      <template #header>
        <div class="card-head">
          <span>{{ $t('entitlement.catalog_title') }}</span>
          <div class="card-head__actions">
            <el-button :disabled="isViewer" @click="capabilityVisible = true">
              {{ $t('entitlement.register_capability') }}
            </el-button>
            <el-button type="primary" :disabled="isViewer" @click="moduleVisible = true">
              {{ $t('entitlement.register_module') }}
            </el-button>
          </div>
        </div>
      </template>
      <p class="hint">{{ $t('entitlement.catalog_hint') }}</p>
      <p class="hint">{{ $t('entitlement.handwritten_hint') }}</p>
      <p class="hint">{{ $t('entitlement.capability_hint') }}</p>
      <el-table v-loading="loading" :data="features" row-key="key" border size="small">
        <el-table-column prop="name" :label="$t('entitlement.feature')" min-width="160" />
        <el-table-column :label="'Key'" min-width="200">
          <template #default="{ row }"><code>{{ row.key }}</code></template>
        </el-table-column>
        <el-table-column :label="$t('entitlement.kind')" width="120">
          <template #default="{ row }">
            <el-tag v-if="featureKind(row) === 'capability'" type="primary" size="small">{{ $t('entitlement.kind_capability') }}</el-tag>
            <el-tag v-else-if="featureKind(row) === 'quota'" type="info" size="small">{{ $t('entitlement.kind_quota') }}</el-tag>
            <el-tag v-else-if="featureKind(row) === 'module'" type="warning" size="small">{{ $t('entitlement.kind_module') }}</el-tag>
            <span v-else>—</span>
          </template>
        </el-table-column>
        <el-table-column prop="type" :label="$t('entitlement.type')" width="100" />
        <el-table-column :label="$t('entitlement.always_on')" width="100">
          <template #default="{ row }">
            <el-tag v-if="row.always_on" type="success" size="small">{{ $t('common.yes') }}</el-tag>
            <span v-else>—</span>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-card shadow="never" class="block">
      <template #header>
        <div class="card-head">
          <span>{{ $t('entitlement.plans_title') }}</span>
          <el-button type="primary" :disabled="isViewer" @click="planVisible = true">
            {{ $t('entitlement.add_plan') }}
          </el-button>
        </div>
      </template>
      <el-table v-loading="loading" :data="plans" row-key="code" border size="small">
        <el-table-column prop="name" :label="$t('entitlement.plan')" min-width="140" />
        <el-table-column :label="'Code'" min-width="120">
          <template #default="{ row }"><code>{{ row.code }}</code></template>
        </el-table-column>
        <el-table-column :label="$t('entitlement.default')" width="100">
          <template #default="{ row }">
            <el-tag v-if="row.is_default" type="success" size="small">{{ $t('common.yes') }}</el-tag>
            <span v-else>—</span>
          </template>
        </el-table-column>
        <el-table-column :label="$t('common.actions')" width="160">
          <template #default="{ row }">
            <el-button link type="primary" :disabled="isViewer" @click="openPlanEntitlements(row)">
              {{ $t('entitlement.edit_plan_entitlements') }}
            </el-button>
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <el-dialog v-model="moduleVisible" :title="$t('entitlement.register_module')" width="520px" destroy-on-close @closed="resetModuleForm">
      <p class="hint">{{ $t('entitlement.handwritten_hint') }}</p>
      <el-form ref="moduleFormRef" :model="moduleForm" :rules="moduleRules" label-width="110px">
        <el-form-item :label="$t('entitlement.module_name')" prop="module_name">
          <el-input v-model="moduleForm.module_name" placeholder="guestbook" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.feature')" prop="display_name">
          <el-input v-model="moduleForm.display_name" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.menu_slugs')" prop="menu_slug">
          <el-input v-model="moduleForm.menu_slug" placeholder="guestbook" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.always_on')" prop="always_on">
          <el-switch v-model="moduleForm.always_on" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.row_quota')" prop="row_quota">
          <el-switch v-model="moduleForm.row_quota" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="moduleVisible = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="saving" @click="submitModule">{{ $t('common.confirm') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="capabilityVisible" :title="$t('entitlement.register_capability')" width="520px" destroy-on-close @closed="resetCapabilityForm">
      <p class="hint">{{ $t('entitlement.capability_hint') }}</p>
      <el-form ref="capabilityFormRef" :model="capabilityForm" :rules="capabilityRules" label-width="110px">
        <el-form-item :label="$t('entitlement.module_name')" prop="module_name">
          <el-autocomplete
            v-model="capabilityForm.module_name"
            :fetch-suggestions="queryModuleOptions"
            placeholder="member"
            style="width: 100%"
          />
        </el-form-item>
        <el-form-item :label="$t('entitlement.capability_name')" prop="capability">
          <el-input v-model="capabilityForm.capability" placeholder="export" />
          <div class="form-extra">{{ $t('entitlement.capability_key_preview') }}</div>
        </el-form-item>
        <el-form-item :label="$t('entitlement.feature')" prop="display_name">
          <el-input v-model="capabilityForm.display_name" placeholder="Member export" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.always_on')" prop="always_on">
          <el-switch v-model="capabilityForm.always_on" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="capabilityVisible = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="saving" @click="submitCapability">{{ $t('common.confirm') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="planVisible" :title="$t('entitlement.add_plan')" width="520px" destroy-on-close @closed="resetPlanForm">
      <el-form ref="planFormRef" :model="planForm" :rules="planRules" label-width="110px">
        <el-form-item label="Code" prop="code">
          <el-input v-model="planForm.code" placeholder="pro" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.plan')" prop="name">
          <el-input v-model="planForm.name" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.description')" prop="description">
          <el-input v-model="planForm.description" type="textarea" :rows="2" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.default')" prop="is_default">
          <el-switch v-model="planForm.is_default" />
        </el-form-item>
        <el-form-item :label="$t('entitlement.price_monthly')" prop="price_monthly">
          <el-input-number v-model="planForm.price_monthly" :min="0" style="width: 100%" />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="planVisible = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="saving" @click="submitPlan">{{ $t('common.confirm') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="planEntVisible" :title="$t('entitlement.edit_plan_entitlements')" width="640px" destroy-on-close>
      <p class="hint">{{ $t('entitlement.plan_entitlements_hint') }}</p>
      <el-input
        v-model="planEntText"
        type="textarea"
        :rows="12"
        :placeholder="'module.guestbook=true\nquota.module.guestbook.rows=1000'"
      />
      <template #footer>
        <el-button @click="planEntVisible = false">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="saving" @click="submitPlanEntitlements">{{ $t('common.confirm') }}</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import {
  getPlatformFeatures,
  getPlatformPlanEntitlements,
  getPlatformPlans,
  registerPlatformCapability,
  registerPlatformModuleFeature,
  updatePlatformPlan,
  upsertPlatformPlan
} from '@/api/platform'
import { getPlatformAdmin } from '@/utils/platformRequest'

const { t } = useI18n()
const isViewer = computed(() => getPlatformAdmin()?.role === 'viewer')

const features = ref([])
const plans = ref([])
const loading = ref(false)
const saving = ref(false)

const moduleVisible = ref(false)
const capabilityVisible = ref(false)
const planVisible = ref(false)
const planEntVisible = ref(false)
const editingPlan = ref(null)
const planEntText = ref('')

const moduleFormRef = ref()
const capabilityFormRef = ref()
const planFormRef = ref()

const moduleForm = reactive({
  module_name: '',
  display_name: '',
  menu_slug: '',
  always_on: false,
  row_quota: false
})
const capabilityForm = reactive({
  module_name: '',
  capability: '',
  display_name: '',
  always_on: false
})
const planForm = reactive({
  code: '',
  name: '',
  description: '',
  is_default: false,
  price_monthly: 0
})

const resetModuleForm = () => {
  Object.assign(moduleForm, { module_name: '', display_name: '', menu_slug: '', always_on: false, row_quota: false })
}
const resetCapabilityForm = () => {
  Object.assign(capabilityForm, { module_name: '', capability: '', display_name: '', always_on: false })
}
const resetPlanForm = () => {
  Object.assign(planForm, { code: '', name: '', description: '', is_default: false, price_monthly: 0 })
}

// Keep module.{a}.{b} within the backend feature key length limit (63).
const segmentPattern = /^[A-Za-z][A-Za-z0-9_-]{0,23}$/
const segmentRule = {
  validator: (_r, v, cb) => {
    if (!v || segmentPattern.test(String(v).trim())) cb()
    else cb(new Error(t('entitlement.capability_name_invalid')))
  },
  trigger: 'blur'
}
const requiredRule = { required: true, message: () => t('common.required'), trigger: 'blur' }

const moduleRules = {
  module_name: [requiredRule]
}
const capabilityRules = {
  module_name: [requiredRule, segmentRule],
  capability: [requiredRule, segmentRule]
}
const planRules = {
  code: [requiredRule],
  name: [requiredRule]
}

const featureKind = (row) => {
  const key = String(row?.key || '')
  if (key.startsWith('quota.')) return 'quota'
  if (key.startsWith('module.') && key.split('.').length >= 3) return 'capability'
  if (key.startsWith('module.')) return 'module'
  return 'other'
}

const moduleOptions = computed(() =>
  features.value
    .filter((f) => featureKind(f) === 'module')
    .map((f) => {
      const name = String(f.key || '').replace(/^module\./, '')
      return { value: name, label: f.name ? `${f.name} (${name})` : name }
    })
)

const queryModuleOptions = (query, cb) => {
  const q = String(query || '').toLowerCase()
  cb(moduleOptions.value.filter((o) => !q || o.value.toLowerCase().includes(q) || o.label.toLowerCase().includes(q)))
}

const pickList = (res) => res?.data?.list || res?.list || []

const reportError = (e) => {
  if (!e?.__handled) ElMessage.error(e?.message || t('common.operation_failed'))
}

const load = async () => {
  loading.value = true
  try {
    const [fRes, pRes] = await Promise.all([getPlatformFeatures(), getPlatformPlans()])
    features.value = pickList(fRes)
    plans.value = pickList(pRes)
  } catch (e) {
    reportError(e)
  } finally {
    loading.value = false
  }
}

const submitModule = async () => {
  try {
    await moduleFormRef.value?.validate()
  } catch {
    return
  }
  saving.value = true
  try {
    await registerPlatformModuleFeature({
      module_name: moduleForm.module_name,
      display_name: moduleForm.display_name,
      menu_slug: moduleForm.menu_slug,
      always_on: !!moduleForm.always_on,
      row_quota: !!moduleForm.row_quota
    })
    ElMessage.success(t('entitlement.module_registered'))
    moduleVisible.value = false
    await load()
  } catch (e) {
    reportError(e)
  } finally {
    saving.value = false
  }
}

const submitCapability = async () => {
  try {
    await capabilityFormRef.value?.validate()
  } catch {
    return
  }
  saving.value = true
  try {
    await registerPlatformCapability({
      module_name: capabilityForm.module_name,
      capability: capabilityForm.capability,
      display_name: capabilityForm.display_name,
      always_on: !!capabilityForm.always_on
    })
    ElMessage.success(t('entitlement.capability_registered'))
    capabilityVisible.value = false
    await load()
  } catch (e) {
    reportError(e)
  } finally {
    saving.value = false
  }
}

const submitPlan = async () => {
  try {
    await planFormRef.value?.validate()
  } catch {
    return
  }
  saving.value = true
  try {
    await upsertPlatformPlan({
      ...planForm,
      is_public: true,
      status: 1
    })
    ElMessage.success(t('common.save_success'))
    planVisible.value = false
    await load()
  } catch (e) {
    reportError(e)
  } finally {
    saving.value = false
  }
}

const openPlanEntitlements = async (plan) => {
  editingPlan.value = plan
  planEntVisible.value = true
  try {
    const res = await getPlatformPlanEntitlements(plan.code)
    const list = pickList(res)
    planEntText.value =
      list.length > 0
        ? list
            .map((row) => {
              const key = String(row.feature_key || '').trim()
              return key ? `${key}=${String(row.value ?? '')}` : ''
            })
            .filter(Boolean)
            .join('\n')
        : features.value
            .map((f) => {
              if (f.type === 'boolean') return `${f.key}=false`
              if (f.type === 'limit') return `${f.key}=0`
              return ''
            })
            .filter(Boolean)
            .join('\n')
  } catch (e) {
    reportError(e)
    planEntText.value = ''
  }
}

const submitPlanEntitlements = async () => {
  if (!editingPlan.value) return
  const entitlements = {}
  String(planEntText.value || '')
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .forEach((line) => {
      const idx = line.indexOf('=')
      if (idx <= 0) return
      const key = line.slice(0, idx).trim()
      const value = line.slice(idx + 1).trim()
      if (key) entitlements[key] = value
    })
  saving.value = true
  try {
    await updatePlatformPlan(editingPlan.value.code, {
      code: editingPlan.value.code,
      name: editingPlan.value.name,
      description: editingPlan.value.description,
      is_default: editingPlan.value.is_default,
      status: editingPlan.value.status || 1,
      entitlements
    })
    ElMessage.success(t('entitlement.plan_entitlements_saved'))
    planEntVisible.value = false
    await load()
  } catch (e) {
    reportError(e)
  } finally {
    saving.value = false
  }
}

onMounted(load)
</script>

<style scoped>
.block {
  margin-bottom: 16px;
}
.card-head {
  display: flex;
  align-items: center;
  justify-content: space-between;
}
.card-head__actions {
  display: flex;
  gap: 8px;
}
.hint {
  margin: 0 0 8px;
  color: var(--el-text-color-secondary);
  font-size: 13px;
}
.form-extra {
  margin-top: 4px;
  font-size: 12px;
  color: var(--el-text-color-secondary);
}
</style>

// html-react/src/pages/platform/Entitlements.tsx
import { AutoComplete, Button, Card, Form, Input, InputNumber, Modal, Space, Switch, Table, Tag, message } from 'antd'
import { useCallback, useEffect, useState } from 'react'
import { useTranslation } from 'react-i18next'
import {
  getPlatformFeatures,
  getPlatformPlanEntitlements,
  getPlatformPlans,
  registerPlatformCapability,
  registerPlatformModuleFeature,
  updatePlatformPlan,
  upsertPlatformPlan,
} from '@/api/platform'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { getPlatformAdmin } from '@/utils/platformRequest'

type Feature = {
  id?: number
  key: string
  name: string
  description?: string
  type: string
  default_value?: string
  menu_slugs?: string[]
  always_on?: boolean
  status?: number
}

type Plan = {
  id?: number
  code: string
  name: string
  description?: string
  is_default?: boolean
  status?: number
}

export default function PlatformEntitlementsPage() {
  const { t } = useTranslation()
  const showError = useUnhandledError()
  const isViewer = getPlatformAdmin()?.role === 'viewer'
  const [features, setFeatures] = useState<Feature[]>([])
  const [plans, setPlans] = useState<Plan[]>([])
  const [loading, setLoading] = useState(false)
  const [moduleOpen, setModuleOpen] = useState(false)
  const [capabilityOpen, setCapabilityOpen] = useState(false)
  const [planOpen, setPlanOpen] = useState(false)
  const [planEntOpen, setPlanEntOpen] = useState(false)
  const [editingPlan, setEditingPlan] = useState<Plan | null>(null)
  const [moduleForm] = Form.useForm()
  const [capabilityForm] = Form.useForm()
  const [planForm] = Form.useForm()
  const [planEntForm] = Form.useForm()

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const [fRes, pRes] = await Promise.all([getPlatformFeatures(), getPlatformPlans()])
      setFeatures(
        ((fRes as { data?: { list?: Feature[] } })?.data?.list ||
          (fRes as { list?: Feature[] })?.list ||
          []) as Feature[],
      )
      setPlans(
        ((pRes as { data?: { list?: Plan[] } })?.data?.list ||
          (pRes as { list?: Plan[] })?.list ||
          []) as Plan[],
      )
    } catch (e) {
      showError(e, t('common.operation_failed'))
    } finally {
      setLoading(false)
    }
  }, [showError, t])

  useEffect(() => {
    void load()
  }, [load])

  const submitModule = async () => {
    try {
      const values = await moduleForm.validateFields()
      await registerPlatformModuleFeature({
        module_name: values.module_name,
        display_name: values.display_name,
        menu_slug: values.menu_slug,
        always_on: !!values.always_on,
        row_quota: !!values.row_quota,
      })
      message.success(t('entitlement.module_registered'))
      setModuleOpen(false)
      moduleForm.resetFields()
      await load()
    } catch (e) {
      if (e && typeof e === 'object' && 'errorFields' in e) return
      showError(e, t('common.operation_failed'))
    }
  }

  const submitCapability = async () => {
    try {
      const values = await capabilityForm.validateFields()
      await registerPlatformCapability({
        module_name: values.module_name,
        capability: values.capability,
        display_name: values.display_name,
        always_on: !!values.always_on,
      })
      message.success(t('entitlement.capability_registered'))
      setCapabilityOpen(false)
      capabilityForm.resetFields()
      await load()
    } catch (e) {
      if (e && typeof e === 'object' && 'errorFields' in e) return
      showError(e, t('common.operation_failed'))
    }
  }

  const featureKind = (row: Feature) => {
    const key = String(row.key || '')
    if (key.startsWith('quota.')) return 'quota'
    if (key.startsWith('module.') && key.split('.').length >= 3) return 'capability'
    if (key.startsWith('module.')) return 'module'
    return 'other'
  }

  const moduleOptions = features
    .filter((f) => featureKind(f) === 'module')
    .map((f) => {
      const name = String(f.key || '').replace(/^module\./, '')
      return { value: name, label: f.name ? `${f.name} (${name})` : name }
    })

  const submitPlan = async () => {
    try {
      const values = await planForm.validateFields()
      await upsertPlatformPlan({
        ...values,
        is_public: true,
        status: 1,
      })
      message.success(t('common.save_success'))
      setPlanOpen(false)
      planForm.resetFields()
      await load()
    } catch (e) {
      if (e && typeof e === 'object' && 'errorFields' in e) return
      showError(e, t('common.operation_failed'))
    }
  }

  const openPlanEntitlements = async (plan: Plan) => {
    setEditingPlan(plan)
    setPlanEntOpen(true)
    try {
      const res = await getPlatformPlanEntitlements(plan.code)
      const list = ((res as { data?: { list?: { feature_key?: string; value?: string }[] } })?.data?.list ||
        (res as { list?: { feature_key?: string; value?: string }[] })?.list ||
        []) as { feature_key?: string; value?: string }[]
      const lines =
        list.length > 0
          ? list
              .map((row) => {
                const key = String(row.feature_key || '').trim()
                if (!key) return ''
                return `${key}=${String(row.value ?? '')}`
              })
              .filter(Boolean)
              .join('\n')
          : features
              .map((f) => {
                if (f.type === 'boolean') return `${f.key}=false`
                if (f.type === 'limit') return `${f.key}=0`
                return ''
              })
              .filter(Boolean)
              .join('\n')
      planEntForm.setFieldsValue({ entitlements_text: lines })
    } catch (e) {
      showError(e, t('common.operation_failed'))
      planEntForm.setFieldsValue({ entitlements_text: '' })
    }
  }

  const submitPlanEntitlements = async () => {
    if (!editingPlan) return
    try {
      const values = await planEntForm.validateFields()
      const entitlements: Record<string, string> = {}
      String(values.entitlements_text || '')
        .split('\n')
        .map((line) => line.trim())
        .filter(Boolean)
        .forEach((line) => {
          const idx = line.indexOf('=')
          if (idx <= 0) return
          const key = line.slice(0, idx).trim()
          const value = line.slice(idx + 1).trim()
          if (key) entitlements[key] = value
        })
      await updatePlatformPlan(editingPlan.code, {
        code: editingPlan.code,
        name: editingPlan.name,
        description: editingPlan.description,
        is_default: editingPlan.is_default,
        status: editingPlan.status || 1,
        entitlements,
      })
      message.success(t('entitlement.plan_entitlements_saved'))
      setPlanEntOpen(false)
      await load()
    } catch (e) {
      if (e && typeof e === 'object' && 'errorFields' in e) return
      showError(e, t('common.operation_failed'))
    }
  }

  return (
    <Space direction="vertical" size="large" style={{ width: '100%' }}>
      <Card
        title={t('entitlement.catalog_title')}
        extra={
          <Space>
            <Button disabled={isViewer} onClick={() => setCapabilityOpen(true)}>
              {t('entitlement.register_capability')}
            </Button>
            <Button type="primary" disabled={isViewer} onClick={() => setModuleOpen(true)}>
              {t('entitlement.register_module')}
            </Button>
          </Space>
        }
      >
        <p style={{ color: 'rgba(0,0,0,0.45)', marginTop: 0 }}>{t('entitlement.catalog_hint')}</p>
        <p style={{ color: 'rgba(0,0,0,0.45)' }}>{t('entitlement.handwritten_hint')}</p>
        <p style={{ color: 'rgba(0,0,0,0.45)' }}>{t('entitlement.capability_hint')}</p>
        <Table
          rowKey="key"
          loading={loading}
          dataSource={features}
          pagination={false}
          columns={[
            { title: t('entitlement.feature'), dataIndex: 'name' },
            { title: 'Key', dataIndex: 'key', render: (v) => <code>{v}</code> },
            {
              title: t('entitlement.kind'),
              width: 120,
              render: (_, row) => {
                const kind = featureKind(row)
                if (kind === 'capability') return <Tag color="blue">{t('entitlement.kind_capability')}</Tag>
                if (kind === 'quota') return <Tag>{t('entitlement.kind_quota')}</Tag>
                if (kind === 'module') return <Tag color="purple">{t('entitlement.kind_module')}</Tag>
                return '—'
              },
            },
            { title: t('entitlement.type'), dataIndex: 'type', width: 100 },
            {
              title: t('entitlement.always_on'),
              dataIndex: 'always_on',
              width: 100,
              render: (v) => (v ? <Tag color="green">{t('common.yes')}</Tag> : '—'),
            },
          ]}
        />
      </Card>

      <Card
        title={t('entitlement.plans_title')}
        extra={
          <Button type="primary" disabled={isViewer} onClick={() => setPlanOpen(true)}>
            {t('entitlement.add_plan')}
          </Button>
        }
      >
        <Table
          rowKey="code"
          loading={loading}
          dataSource={plans}
          pagination={false}
          columns={[
            { title: t('entitlement.plan'), dataIndex: 'name' },
            { title: 'Code', dataIndex: 'code', render: (v) => <code>{v}</code> },
            {
              title: t('entitlement.default'),
              dataIndex: 'is_default',
              width: 100,
              render: (v) => (v ? <Tag color="green">{t('common.yes')}</Tag> : '—'),
            },
            {
              title: t('common.actions'),
              width: 160,
              render: (_, row) => (
                <Button type="link" size="small" disabled={isViewer} onClick={() => void openPlanEntitlements(row)}>
                  {t('entitlement.edit_plan_entitlements')}
                </Button>
              ),
            },
          ]}
        />
      </Card>

      <Modal
        open={moduleOpen}
        title={t('entitlement.register_module')}
        onCancel={() => setModuleOpen(false)}
        onOk={() => void submitModule()}
        destroyOnHidden
      >
        <p style={{ color: 'rgba(0,0,0,0.45)' }}>{t('entitlement.handwritten_hint')}</p>
        <Form form={moduleForm} layout="vertical">
          <Form.Item name="module_name" label={t('entitlement.module_name')} rules={[{ required: true }]}>
            <Input placeholder="guestbook" />
          </Form.Item>
          <Form.Item name="display_name" label={t('entitlement.feature')}>
            <Input />
          </Form.Item>
          <Form.Item name="menu_slug" label={t('entitlement.menu_slugs')}>
            <Input placeholder="guestbook" />
          </Form.Item>
          <Form.Item name="always_on" label={t('entitlement.always_on')} valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item name="row_quota" label={t('entitlement.row_quota')} valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={capabilityOpen}
        title={t('entitlement.register_capability')}
        onCancel={() => setCapabilityOpen(false)}
        onOk={() => void submitCapability()}
        destroyOnHidden
      >
        <p style={{ color: 'rgba(0,0,0,0.45)' }}>{t('entitlement.capability_hint')}</p>
        <Form form={capabilityForm} layout="vertical">
          <Form.Item
            name="module_name"
            label={t('entitlement.module_name')}
            rules={[
              { required: true },
              {
                // Keep module.{a}.{b} within ValidateFeatureKey max length (63).
                pattern: /^[A-Za-z][A-Za-z0-9_-]{0,23}$/,
                message: t('entitlement.capability_name_invalid'),
              },
            ]}
          >
            <AutoComplete options={moduleOptions} placeholder="member" filterOption />
          </Form.Item>
          <Form.Item
            name="capability"
            label={t('entitlement.capability_name')}
            rules={[
              { required: true },
              {
                pattern: /^[A-Za-z][A-Za-z0-9_-]{0,23}$/,
                message: t('entitlement.capability_name_invalid'),
              },
            ]}
            extra={t('entitlement.capability_key_preview')}
          >
            <Input placeholder="export" />
          </Form.Item>
          <Form.Item name="display_name" label={t('entitlement.feature')}>
            <Input placeholder="Member export" />
          </Form.Item>
          <Form.Item name="always_on" label={t('entitlement.always_on')} valuePropName="checked">
            <Switch />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={planOpen}
        title={t('entitlement.add_plan')}
        onCancel={() => setPlanOpen(false)}
        onOk={() => void submitPlan()}
        destroyOnHidden
      >
        <Form form={planForm} layout="vertical">
          <Form.Item name="code" label="Code" rules={[{ required: true }]}>
            <Input placeholder="pro" />
          </Form.Item>
          <Form.Item name="name" label={t('entitlement.plan')} rules={[{ required: true }]}>
            <Input />
          </Form.Item>
          <Form.Item name="description" label={t('entitlement.description')}>
            <Input.TextArea rows={2} />
          </Form.Item>
          <Form.Item name="is_default" label={t('entitlement.default')} valuePropName="checked">
            <Switch />
          </Form.Item>
          <Form.Item name="price_monthly" label={t('entitlement.price_monthly')}>
            <InputNumber min={0} style={{ width: '100%' }} />
          </Form.Item>
        </Form>
      </Modal>

      <Modal
        open={planEntOpen}
        title={t('entitlement.edit_plan_entitlements')}
        onCancel={() => setPlanEntOpen(false)}
        onOk={() => void submitPlanEntitlements()}
        width={640}
        destroyOnHidden
      >
        <p style={{ color: 'rgba(0,0,0,0.45)' }}>{t('entitlement.plan_entitlements_hint')}</p>
        <Form form={planEntForm} layout="vertical">
          <Form.Item name="entitlements_text" label={t('entitlement.plan_entitlements')}>
            <Input.TextArea rows={12} placeholder={'module.guestbook=true\nquota.module.guestbook.rows=1000'} />
          </Form.Item>
        </Form>
      </Modal>
    </Space>
  )
}
