// html/src/views/platform/OperationLogList.vue
<template>
  <ListPage
    page-class="platform-operation-log"
    :title="$t('menu.operation_log')"
    :show-add-button="false"
    :search-form="searchForm"
    :search-fields="searchFields"
    :initial-search-values="initialSearchForm"
    i18n-prefix="log"
    :table-data="tableData"
    :loading="loading"
    :table-columns="tableColumns"
    :pagination="pagination"
    show-toolbar
    @search="handleSearch"
    @reset="handleReset"
    @refresh="loadData"
    @page-change="loadData"
    @sort-change="handleSortChange"
  >
    <template #status="{ row }">
      <el-tag :type="Number(row.status) === 1 ? 'success' : 'danger'" size="small">
        {{ Number(row.status) === 1 ? $t('log.success') : $t('log.failed') }}
      </el-tag>
    </template>
    <template #title="{ row }">
      {{ translateTitle(row.title) }}
    </template>
    <template #operation="{ row }">
      <el-button link type="primary" @click="handleView(row)">{{ $t('common.view') }}</el-button>
    </template>
  </ListPage>

  <el-dialog v-model="detailVisible" :title="$t('log.detail')" width="900px" destroy-on-close>
    <el-descriptions v-if="logDetail" :column="2" border>
      <el-descriptions-item :label="$t('table.id')">{{ logDetail.id }}</el-descriptions-item>
      <el-descriptions-item :label="$t('log.admin')">{{ logDetail.username || '-' }}</el-descriptions-item>
      <el-descriptions-item :label="$t('log.method')">{{ logDetail.method || '-' }}</el-descriptions-item>
      <el-descriptions-item :label="$t('log.title')">{{ translateTitle(logDetail.title) }}</el-descriptions-item>
      <el-descriptions-item :label="$t('log.path')" :span="2">{{ logDetail.path || '-' }}</el-descriptions-item>
      <el-descriptions-item :label="$t('log.ip')">{{ logDetail.ip || '-' }}</el-descriptions-item>
      <el-descriptions-item :label="$t('table.status')">
        <el-tag :type="Number(logDetail.status) === 1 ? 'success' : 'danger'" size="small">
          {{ Number(logDetail.status) === 1 ? $t('log.success') : $t('log.failed') }}
        </el-tag>
      </el-descriptions-item>
      <el-descriptions-item :label="$t('log.operation_time')">{{ logDetail.created_at || '-' }}</el-descriptions-item>
      <el-descriptions-item label="Duration">{{ logDetail.duration ?? '-' }} ms</el-descriptions-item>
      <el-descriptions-item :label="$t('log.user_agent')" :span="2">{{ logDetail.user_agent || '-' }}</el-descriptions-item>
      <el-descriptions-item :label="$t('log.request')" :span="2">
        <pre v-if="logDetail.request" class="request-preview">{{ formatRequest(logDetail.request) }}</pre>
        <span v-else>-</span>
      </el-descriptions-item>
    </el-descriptions>
  </el-dialog>
</template>

<script setup>
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import ListPage from '@/components/ListPage.vue'
import { useStandardListPage } from '@/composables/useStandardListPage'
import { getPlatformOperationLogDetail, getPlatformOperationLogList } from '@/api/platform'
import { translatePlatformOpTitle } from '@/utils/platformOpTitle'

const { t, te } = useI18n()
const translateTitle = (title) => translatePlatformOpTitle(t, te, title)
const initialSearchForm = {
  username: '',
  method: '',
  path: '',
  status: '',
}

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
} = useStandardListPage({
  fetchApi: getPlatformOperationLogList,
  initialSearchForm,
  defaultSort: 'id:desc',
})

const detailVisible = ref(false)
const logDetail = ref(null)

const searchFields = computed(() => [
  { prop: 'username', label: t('log.admin'), type: 'input', width: '140px' },
  {
    prop: 'method',
    label: t('log.method'),
    type: 'select',
    width: '120px',
    options: [
      { label: 'POST', value: 'POST' },
      { label: 'PUT', value: 'PUT' },
      { label: 'PATCH', value: 'PATCH' },
      { label: 'DELETE', value: 'DELETE' },
    ],
  },
  { prop: 'path', label: t('log.path'), type: 'input', width: '180px' },
  {
    prop: 'status',
    label: t('table.status'),
    type: 'select',
    width: '120px',
    options: [
      { label: t('log.success'), value: '1' },
      { label: t('log.failed'), value: '0' },
    ],
  },
])

const tableColumns = computed(() => [
  { field: 'id', title: t('table.id'), width: 70, sortable: true, key: 'id' },
  { field: 'username', title: t('log.admin'), width: 120, key: 'username' },
  { field: 'method', title: t('log.method'), width: 90, key: 'method' },
  { field: 'title', title: t('log.title'), minWidth: 180, slot: 'title', key: 'title' },
  { field: 'path', title: t('log.path'), minWidth: 200, key: 'path' },
  { field: 'ip', title: t('log.ip'), width: 130, key: 'ip' },
  { field: 'status', title: t('table.status'), width: 90, slot: 'status', key: 'status' },
  { field: 'duration', title: 'ms', width: 80, key: 'duration' },
  { field: 'created_at', title: t('log.operation_time'), width: 170, key: 'created_at' },
  { field: 'operation', title: t('table.operation'), width: 90, slot: 'operation', key: 'operation', fixed: 'right' },
])

const formatRequest = (raw) => {
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    return String(raw || '')
  }
}

const handleView = async (row) => {
  try {
    const res = await getPlatformOperationLogDetail(row.id)
    logDetail.value = res?.data?.operation_log || res?.data || row
    detailVisible.value = true
  } catch (e) {
    console.error(e)
  }
}
</script>

<style scoped>
.request-preview {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  max-height: 280px;
  overflow: auto;
}
</style>

// html-react/src/pages/platform/OperationLogList.tsx
import { useMemo, useState } from 'react'
import { Button, Descriptions, Modal, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useTranslation } from 'react-i18next'
import { getPlatformOperationLogDetail, getPlatformOperationLogList } from '@/api/platform'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { entityField } from '@/utils/normalize'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import { translatePlatformOpTitle } from '@/utils/platformOpTitle'

interface OperationLogRow {
  id: number | string
  username?: string
  method?: string
  path?: string
  title?: string
  ip?: string
  status?: number | string
  duration?: number
  user_agent?: string
  request?: string
  created_at?: string
}

function formatRequest(raw?: string) {
  if (!raw) return ''
  try {
    return JSON.stringify(JSON.parse(raw), null, 2)
  } catch {
    return raw
  }
}

export default function PlatformOperationLogList() {
  const { t, i18n } = useTranslation()
  const translateTitle = (title?: string) =>
    translatePlatformOpTitle(t, (key) => i18n.exists(key), title)
  const [detailOpen, setDetailOpen] = useState(false)
  const [detail, setDetail] = useState<OperationLogRow | null>(null)
  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
  } = useListPage<OperationLogRow>({
    fetchApi: getPlatformOperationLogList,
    initialSearchForm: { username: '', method: '', path: '', status: '' },
    defaultSort: 'id:desc',
    transformData: (row) => ({
      id: entityField(row, 'id', '')!,
      username: String(entityField(row, 'username', '') ?? ''),
      method: String(entityField(row, 'method', '') ?? ''),
      path: String(entityField(row, 'path', '') ?? ''),
      title: String(entityField(row, 'title', '') ?? ''),
      ip: String(entityField(row, 'ip', '') ?? ''),
      status: entityField(row, 'status', 0) as number | string,
      duration: Number(entityField(row, 'duration', 0) ?? 0),
      user_agent: String(entityField(row, 'user_agent', '') ?? ''),
      request: String(entityField(row, 'request', '') ?? ''),
      created_at: String(entityField(row, 'created_at', '') ?? ''),
    }),
  })

  const columns: ColumnsType<OperationLogRow> = useMemo(
    () => [
      { title: t('table.id'), dataIndex: 'id', width: 70, sorter: true },
      { title: t('log.admin'), dataIndex: 'username', width: 120 },
      { title: t('log.method'), dataIndex: 'method', width: 90 },
      { title: t('log.title'), dataIndex: 'title', ellipsis: true, render: (v: string) => translateTitle(v) },
      { title: t('log.path'), dataIndex: 'path', ellipsis: true },
      { title: t('log.ip'), dataIndex: 'ip', width: 130 },
      {
        title: t('table.status'),
        dataIndex: 'status',
        width: 90,
        render: (v) => (
          <Tag color={Number(v) === 1 ? 'success' : 'error'}>
            {Number(v) === 1 ? t('log.success') : t('log.failed')}
          </Tag>
        ),
      },
      { title: 'ms', dataIndex: 'duration', width: 80 },
      { title: t('log.operation_time'), dataIndex: 'created_at', width: 170 },
      {
        title: t('table.operation'),
        key: 'action',
        width: 90,
        fixed: 'right',
        render: (_, row) => (
          <Button
            type="link"
            onClick={async () => {
              try {
                const res = await getPlatformOperationLogDetail(row.id)
                const data = (res as { data?: { operation_log?: OperationLogRow } & OperationLogRow })?.data
                setDetail(data?.operation_log || data || row)
                setDetailOpen(true)
              } catch {
                setDetail(row)
                setDetailOpen(true)
              }
            }}
          >
            {t('common.view')}
          </Button>
        ),
      },
    ],
    [t, i18n],
  )

  return (
    <PageContainer title={t('menu.operation_log')}>
      <SearchForm
        fields={[
          { name: 'username', label: t('log.admin'), type: 'input' },
          {
            name: 'method',
            label: t('log.method'),
            type: 'select',
            options: [
              { label: 'POST', value: 'POST' },
              { label: 'PUT', value: 'PUT' },
              { label: 'PATCH', value: 'PATCH' },
              { label: 'DELETE', value: 'DELETE' },
            ],
          },
          { name: 'path', label: t('log.path'), type: 'input' },
          {
            name: 'status',
            label: t('table.status'),
            type: 'select',
            options: [
              { label: t('log.success'), value: '1' },
              { label: t('log.failed'), value: '0' },
            ],
          },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
        }}
        scroll={{ x: 1200 }}
        onChange={(pager, _f, sorter) => {
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }}
      />
      <Modal
        title={t('log.detail')}
        open={detailOpen}
        onCancel={() => setDetailOpen(false)}
        footer={null}
        width={900}
        destroyOnClose
      >
        {detail ? (
          <Descriptions bordered size="small" column={2}>
            <Descriptions.Item label={t('table.id')}>{detail.id}</Descriptions.Item>
            <Descriptions.Item label={t('log.admin')}>{detail.username || '-'}</Descriptions.Item>
            <Descriptions.Item label={t('log.method')}>{detail.method || '-'}</Descriptions.Item>
            <Descriptions.Item label={t('log.title')}>{translateTitle(detail.title)}</Descriptions.Item>
            <Descriptions.Item label={t('log.path')} span={2}>
              {detail.path || '-'}
            </Descriptions.Item>
            <Descriptions.Item label={t('log.ip')}>{detail.ip || '-'}</Descriptions.Item>
            <Descriptions.Item label={t('table.status')}>
              <Tag color={Number(detail.status) === 1 ? 'success' : 'error'}>
                {Number(detail.status) === 1 ? t('log.success') : t('log.failed')}
              </Tag>
            </Descriptions.Item>
            <Descriptions.Item label={t('log.operation_time')}>{detail.created_at || '-'}</Descriptions.Item>
            <Descriptions.Item label="Duration">{detail.duration ?? '-'} ms</Descriptions.Item>
            <Descriptions.Item label={t('log.user_agent')} span={2}>
              {detail.user_agent || '-'}
            </Descriptions.Item>
            <Descriptions.Item label={t('log.request')} span={2}>
              <pre style={{ margin: 0, whiteSpace: 'pre-wrap', maxHeight: 280, overflow: 'auto' }}>
                {formatRequest(detail.request) || '-'}
              </pre>
            </Descriptions.Item>
          </Descriptions>
        ) : null}
      </Modal>
    </PageContainer>
  )
}
