// html/src/views/platform/Settings.vue
<template>
  <div class="platform-settings">
    <el-card shadow="never" v-loading="loading">
      <template #header>{{ $t('platform.settings_captcha_title') }}</template>
      <el-alert
        v-if="isViewer"
        type="info"
        show-icon
        :closable="false"
        :title="$t('platform.settings_viewer_hint')"
        style="margin-bottom: 16px"
      />
      <el-form :model="form" label-width="120px" label-position="left" :disabled="isViewer">
        <el-form-item :label="$t('config.captcha_type')" prop="captcha_type">
          <el-select v-model="form.captcha_type" style="width: 240px">
            <el-option :label="$t('config.captcha_type_image')" value="image" />
            <el-option :label="$t('config.captcha_type_slide')" value="slide" />
          </el-select>
          <div class="tip">{{ $t('platform.settings_captcha_tip') }}</div>
        </el-form-item>
        <el-form-item v-if="!isViewer">
          <el-button type="primary" :loading="saving" @click="onSave">{{ $t('common.save') }}</el-button>
        </el-form-item>
      </el-form>
    </el-card>
  </div>
</template>

<script setup>
/** Landlord console settings (stored in platform_settings). */
import { computed, onMounted, reactive, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { getPlatformSettings, updatePlatformSettings } from '@/api/platform'
import { getPlatformAdmin } from '@/utils/platformRequest'

const { t } = useI18n()
const loading = ref(false)
const saving = ref(false)
const form = reactive({ captcha_type: 'image' })
const isViewer = computed(() => getPlatformAdmin()?.role === 'viewer')

const load = async () => {
  loading.value = true
  try {
    const res = await getPlatformSettings()
    form.captcha_type = res.data?.settings?.captcha_type === 'slide' ? 'slide' : 'image'
  } catch (error) {
    if (!error?.__handled) {
      ElMessage.error(error?.translatedMessage || error?.message || t('common.operation_failed'))
    }
  } finally {
    loading.value = false
  }
}

const onSave = async () => {
  saving.value = true
  try {
    await updatePlatformSettings({ captcha_type: form.captcha_type })
    ElMessage.success(t('config.update_success'))
  } catch (error) {
    if (!error?.__handled) {
      ElMessage.error(error?.translatedMessage || error?.message || t('common.operation_failed'))
    }
  } finally {
    saving.value = false
  }
}

onMounted(load)
</script>

<style scoped>
.platform-settings {
  padding: 4px;
}
.tip {
  margin-top: 4px;
  font-size: 12px;
  line-height: 1.5;
  color: var(--el-text-color-secondary, #64748b);
}
</style>

// html-react/src/pages/platform/Settings.tsx
import { useCallback, useEffect, useState } from 'react'
import { Alert, Button, Card, Form, Select, message } from 'antd'
import { useTranslation } from 'react-i18next'
import { getPlatformSettings, updatePlatformSettings } from '@/api/platform'
import { getPlatformAdmin } from '@/utils/platformRequest'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'

interface SettingsForm {
  captcha_type: 'image' | 'slide'
}

/** Landlord console settings (stored in platform_settings). */
export default function PlatformSettingsPage() {
  const { t } = useTranslation()
  const showError = useUnhandledError()
  const [form] = Form.useForm<SettingsForm>()
  const [loading, setLoading] = useState(false)
  const [saving, setSaving] = useState(false)
  const isViewer = getPlatformAdmin()?.role === 'viewer'

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const res = await getPlatformSettings()
      const settings = (res as { data?: { settings?: { captcha_type?: string } } })?.data?.settings
      form.setFieldsValue({ captcha_type: settings?.captcha_type === 'slide' ? 'slide' : 'image' })
    } catch (error) {
      showError(error, t('common.query_failed'))
    } finally {
      setLoading(false)
    }
  }, [form, showError, t])

  useEffect(() => {
    void load()
  }, [load])

  const onSave = async () => {
    try {
      const values = await form.validateFields()
      setSaving(true)
      await updatePlatformSettings({ captcha_type: values.captcha_type })
      message.success(t('config.update_success'))
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    } finally {
      setSaving(false)
    }
  }

  return (
    <PageContainer title={t('menu.platform_settings')}>
      <Card title={t('platform.settings_captcha_title')} loading={loading}>
        {isViewer ? (
          <Alert type="info" showIcon style={{ marginBottom: 16 }} message={t('platform.settings_viewer_hint')} />
        ) : null}
        <Form form={form} layout="vertical" disabled={isViewer} style={{ maxWidth: 480 }}>
          <Form.Item
            name="captcha_type"
            label={t('config.captcha_type')}
            extra={t('platform.settings_captcha_tip')}
          >
            <Select
              options={[
                { value: 'image', label: t('config.captcha_type_image') },
                { value: 'slide', label: t('config.captcha_type_slide') },
              ]}
            />
          </Form.Item>
          {!isViewer ? (
            <Button type="primary" loading={saving} onClick={() => void onSave()}>
              {t('common.save')}
            </Button>
          ) : null}
        </Form>
      </Card>
    </PageContainer>
  )
}
