// html-react/src/components/MenuSearch.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Input, Modal } from 'antd'
import { SearchOutlined } from '@ant-design/icons'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'
import { useUserStore } from '@/stores/user'
import { resolveMenuIcon } from '@/utils/menuIcons'
import { resolveMenuTitle } from '@/utils/menuTitle'
import type { MenuNode } from '@/types'
import './MenuSearch.scss'

type SearchableMenu = {
  key: string
  title: string
  path: string
  slug: string
  icon?: string
  linkType: number
  openType: number
}

function isApplePlatform(): boolean {
  if (typeof navigator === 'undefined') return false
  const platform = navigator.platform || ''
  const ua = navigator.userAgent || ''
  return /Mac|iPhone|iPad|iPod/i.test(platform) || /Mac OS X/i.test(ua)
}

function flattenMenus(nodes: MenuNode[], result: MenuNode[] = []): MenuNode[] {
  nodes.forEach((menu) => {
    const menuType = menu.type ?? menu.Type ?? 1
    const path = String(menu.path || menu.Path || '').trim()
    if (menuType === 2 && path) {
      result.push(menu)
    }
    const children = menu.children || menu.Children
    if (children?.length) {
      flattenMenus(children, result)
    }
  })
  return result
}

export default function MenuSearch() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  const menus = useUserStore((s) => s.menus)
  const [open, setOpen] = useState(false)
  const [keyword, setKeyword] = useState('')
  const [selectedIndex, setSelectedIndex] = useState(0)
  const inputRef = useRef<any>(null)

  const shortcutLabel = useMemo(() => (isApplePlatform() ? '\u2318K' : 'Ctrl+K'), [])

  const allMenus = useMemo<SearchableMenu[]>(() => {
    const fromTree = flattenMenus(menus || []).map((menu, index) => {
      const path = String(menu.path || menu.Path || '').trim()
      const slug = String(menu.slug || menu.Slug || '')
      const title = resolveMenuTitle(t, {
        slug,
        fallback: menu.Title || menu.title || menu.Name || menu.name || slug || path,
      })
      return {
        key: `${path}-${menu.id ?? menu.ID ?? index}`,
        title,
        path,
        slug,
        icon: menu.Icon || menu.icon,
        linkType: menu.link_type ?? menu.LinkType ?? 1,
        openType: (menu as { open_type?: number; OpenType?: number }).open_type
          ?? (menu as { OpenType?: number }).OpenType
          ?? 1,
      }
    })

    const dashboard: SearchableMenu = {
      key: 'dashboard',
      title: t('menu.dashboard'),
      path: '/dashboard',
      slug: 'dashboard',
      linkType: 1,
      openType: 1,
    }

    const seen = new Set<string>()
    const merged: SearchableMenu[] = []
    for (const item of [dashboard, ...fromTree]) {
      const id = item.path.toLowerCase()
      if (!id || seen.has(id)) continue
      seen.add(id)
      merged.push(item)
    }
    return merged
  }, [menus, t])

  const filteredMenus = useMemo(() => {
    const q = keyword.trim().toLowerCase()
    if (!q) return allMenus.slice(0, 10)
    return allMenus
      .filter((menu) => {
        return (
          menu.title.toLowerCase().includes(q) ||
          menu.path.toLowerCase().includes(q) ||
          menu.slug.toLowerCase().includes(q)
        )
      })
      .slice(0, 10)
  }, [allMenus, keyword])

  useEffect(() => {
    setSelectedIndex(0)
  }, [keyword, open])

  const close = useCallback(() => {
    setOpen(false)
    setKeyword('')
    setSelectedIndex(0)
  }, [])

  const openPalette = useCallback(() => {
    setOpen(true)
  }, [])

  const handleSelect = useCallback(
    (menu: SearchableMenu) => {
      if (!menu.path) return
      if (menu.linkType === 2) {
        if (menu.openType === 2) {
          window.open(menu.path, '_blank')
        } else {
          navigate(`/iframe?url=${encodeURIComponent(menu.path)}&title=${encodeURIComponent(menu.title)}`)
        }
      } else {
        navigate(menu.path)
      }
      close()
    },
    [close, navigate],
  )

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const key = String(event.key || '').toLowerCase()
      if (key === 'k' && (event.metaKey || event.ctrlKey) && !event.altKey) {
        event.preventDefault()
        setOpen((prev) => {
          if (prev) {
            setKeyword('')
            setSelectedIndex(0)
            return false
          }
          return true
        })
      }
    }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [])

  return (
    <>
      <button
        type="button"
        className="layout-header__icon-btn menu-search-trigger"
        title={`${t('header.menu_search')} (${shortcutLabel})`}
        onClick={openPalette}
      >
        <SearchOutlined />
        <kbd className="menu-search-kbd">{shortcutLabel}</kbd>
      </button>

      <Modal
        open={open}
        onCancel={close}
        footer={null}
        closable={false}
        destroyOnHidden
        width={480}
        centered
        className="menu-search-modal"
        afterOpenChange={(visible) => {
          if (visible) {
            window.setTimeout(() => inputRef.current?.focus?.(), 0)
          }
        }}
      >
        <div className="menu-search-panel">
          <Input
            ref={inputRef}
            allowClear
            size="large"
            prefix={<SearchOutlined />}
            placeholder={t('header.menu_search_placeholder')}
            value={keyword}
            onChange={(e) => setKeyword(e.target.value)}
            onKeyDown={(event) => {
              if (event.key === 'ArrowDown') {
                event.preventDefault()
                setSelectedIndex((prev) => (prev + 1) % Math.max(filteredMenus.length, 1))
              } else if (event.key === 'ArrowUp') {
                event.preventDefault()
                setSelectedIndex((prev) =>
                  prev <= 0 ? Math.max(filteredMenus.length - 1, 0) : prev - 1,
                )
              } else if (event.key === 'Enter') {
                event.preventDefault()
                const target = filteredMenus[selectedIndex] || filteredMenus[0]
                if (target) handleSelect(target)
              } else if (event.key === 'Escape') {
                event.preventDefault()
                close()
              }
            }}
          />

          <div className="menu-search-results">
            {filteredMenus.length > 0 ? (
              filteredMenus.map((menu, index) => (
                <button
                  key={menu.key}
                  type="button"
                  className={`menu-search-item${index === selectedIndex ? ' is-active' : ''}`}
                  onMouseEnter={() => setSelectedIndex(index)}
                  onClick={() => handleSelect(menu)}
                >
                  <span className="menu-search-item__icon">{resolveMenuIcon(menu.icon)}</span>
                  <span className="menu-search-item__title">{menu.title}</span>
                  <span className="menu-search-item__path">{menu.path}</span>
                </button>
              ))
            ) : (
              <div className="menu-search-empty">
                {keyword.trim()
                  ? t('header.menu_search_no_results')
                  : t('header.menu_search_hint')}
              </div>
            )}
          </div>

          <div className="menu-search-footer">
            <span>{t('header.menu_search_shortcut_hint', { shortcut: shortcutLabel })}</span>
          </div>
        </div>
      </Modal>
    </>
  )
}

// html/src/components/MenuSearch.vue
<template>
  <el-popover
    v-model:visible="visible"
    placement="bottom-end"
    :width="400"
    trigger="click"
    popper-class="menu-search-popover"
    :teleported="true"
  >
    <template #reference>
      <el-button
        type="text"
        class="header-btn topbar-icon-btn menu-search-trigger"
        :title="triggerTitle"
      >
        <el-icon class="header-icon-fixed topbar-icon"><Search /></el-icon>
        <kbd class="menu-search-kbd">{{ shortcutLabel }}</kbd>
      </el-button>
    </template>

      <div class="menu-search-content">
        <el-input
          v-model="searchKeyword"
          :placeholder="$t('header.menu_search_placeholder')"
          clearable
          @input="handleSearch"
          @keydown.enter="handleEnter"
          @keydown.down.prevent="handleArrowDown"
          @keydown.up.prevent="handleArrowUp"
          @keydown.esc.stop="visible = false"
          ref="inputRef"
        >
          <template #prefix>
            <el-icon><Search /></el-icon>
          </template>
        </el-input>

        <div class="menu-search-results" v-if="filteredMenus.length > 0">
          <div
            v-for="(menu, index) in filteredMenus"
            :key="menu.id || menu.ID || index"
            class="menu-search-item"
            :class="{ 'is-active': index === selectedIndex }"
            @click="handleMenuClick(menu)"
            @mouseenter="selectedIndex = index"
          >
            <el-icon v-if="getIcon(menu.icon || menu.Icon)" class="menu-item-icon">
              <component :is="getIcon(menu.icon || menu.Icon)" />
            </el-icon>
            <span class="menu-item-title">{{ getMenuTitle(menu) }}</span>
            <span v-if="menu.path || menu.Path" class="menu-item-path">{{ menu.path || menu.Path }}</span>
          </div>
        </div>

        <div v-else class="menu-search-empty">
          {{ searchKeyword ? $t('header.menu_search_no_results') : $t('header.menu_search_hint') }}
        </div>

        <div class="menu-search-footer">
          {{ $t('header.menu_search_shortcut_hint', { shortcut: shortcutLabel }) }}
        </div>
      </div>
    </el-popover>
</template>

<script setup>
import { ref, computed, watch, nextTick, onMounted, onBeforeUnmount } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { Search } from '@element-plus/icons-vue'
import * as ElementPlusIconsVue from '@element-plus/icons-vue'
import { getMenuTitle as getMenuTitleUtil } from '../utils/menuTranslation'

const router = useRouter()
const { t, te } = useI18n()

const props = defineProps({
  menus: {
    type: Array,
    default: () => []
  }
})

const visible = ref(false)
const searchKeyword = ref('')
const selectedIndex = ref(-1)
const inputRef = ref(null)

const isApplePlatform = () => {
  if (typeof navigator === 'undefined') return false
  const platform = navigator.platform || ''
  const ua = navigator.userAgent || ''
  return /Mac|iPhone|iPad|iPod/i.test(platform) || /Mac OS X/i.test(ua)
}

const shortcutLabel = computed(() => (isApplePlatform() ? '\u2318K' : 'Ctrl+K'))
const triggerTitle = computed(() => `${t('header.menu_search')} (${shortcutLabel.value})`)

const onGlobalKeydown = (event) => {
  const key = String(event.key || '').toLowerCase()
  if (key === 'k' && (event.metaKey || event.ctrlKey) && !event.altKey) {
    event.preventDefault()
    visible.value = !visible.value
    return
  }
  if (key === 'escape' && visible.value) {
    visible.value = false
  }
}

onMounted(() => {
  window.addEventListener('keydown', onGlobalKeydown)
})

onBeforeUnmount(() => {
  window.removeEventListener('keydown', onGlobalKeydown)
})

// Flatten menu tree for search (type=2 leaf menus with path only).
const flattenMenus = (menus, result = []) => {
  menus.forEach((menu) => {
    const menuType = menu.type !== undefined ? menu.type : (menu.Type !== undefined ? menu.Type : 1)
    const path = (menu.path || menu.Path || '').trim()
    if (menuType === 2 && path !== '') {
      result.push(menu)
    }
    const children = menu.children || menu.Children
    if (children && children.length > 0) {
      flattenMenus(children, result)
    }
  })
  return result
}

// 所有可搜索的菜单
const allMenus = computed(() => {
  return flattenMenus(props.menus || [])
})

// 过滤后的菜单
const filteredMenus = computed(() => {
  if (!searchKeyword.value || searchKeyword.value.trim() === '') {
    return allMenus.value.slice(0, 10)
  }

  const keyword = searchKeyword.value.toLowerCase().trim()
  return allMenus.value.filter(menu => {
    const title = getMenuTitle(menu).toLowerCase()
    const path = (menu.path || menu.Path || '').toLowerCase()
    const slug = ((menu.slug || menu.Slug) || '').toLowerCase()

    return title.includes(keyword) ||
           path.includes(keyword) ||
           slug.includes(keyword)
  }).slice(0, 10)
})

// 获取菜单标题
const getMenuTitle = (menu) => {
  return getMenuTitleUtil(t, te, menu)
}

// 获取图标
const normalizeIconName = (iconName) => {
  if (!iconName) return ''
  const trimmed = iconName.trim()
  if (!trimmed) return ''
  if (ElementPlusIconsVue[trimmed]) return trimmed
  const pascalCase = trimmed.charAt(0).toUpperCase() + trimmed.slice(1)
  if (ElementPlusIconsVue[pascalCase]) return pascalCase
  return ''
}

const getIcon = (iconName) => {
  const normalized = normalizeIconName(iconName)
  return normalized ? ElementPlusIconsVue[normalized] : null
}

// 处理搜索
const handleSearch = () => {
  selectedIndex.value = -1
}

// 处理菜单点击
const handleMenuClick = (menu) => {
  // 检查菜单类型和路径
  const menuType = menu.type !== undefined ? menu.type : (menu.Type !== undefined ? menu.Type : 1)
  
  // 如果是目录类型（type === 1）或按钮类型（type === 3），不处理
  if (menuType === 1 || menuType === 3) {
    return
  }
  
  if (!menu.path && !menu.Path) {
    return
  }
  const path = (menu.path || menu.Path || '').trim()
  if (!path) {
    return
  }

  const linkType = menu.link_type !== undefined ? menu.link_type : (menu.LinkType !== undefined ? menu.LinkType : 1)
  const openType = menu.open_type !== undefined ? menu.open_type : (menu.OpenType !== undefined ? menu.OpenType : 1)

  if (linkType === 2) {
    if (openType === 1) {
      const title = getMenuTitle(menu)
      const iframePath = `/iframe?url=${encodeURIComponent(path)}&title=${encodeURIComponent(title)}`
      router.push(iframePath)
    } else if (openType === 2) {
      window.open(path, '_blank')
    }
  } else {
    router.push(path)
  }

  visible.value = false
  searchKeyword.value = ''
}

// 处理回车键
const handleEnter = () => {
  if (selectedIndex.value >= 0 && filteredMenus.value[selectedIndex.value]) {
    handleMenuClick(filteredMenus.value[selectedIndex.value])
  } else if (filteredMenus.value.length > 0) {
    handleMenuClick(filteredMenus.value[0])
  }
}

// 处理下箭头
const handleArrowDown = () => {
  if (selectedIndex.value < filteredMenus.value.length - 1) {
    selectedIndex.value++
  } else {
    selectedIndex.value = 0
  }
}

// 处理上箭头
const handleArrowUp = () => {
  if (selectedIndex.value > 0) {
    selectedIndex.value--
  } else {
    selectedIndex.value = filteredMenus.value.length - 1
  }
}

// 监听弹窗打开，自动聚焦输入框
watch(visible, (newVal) => {
  if (newVal) {
    nextTick(() => {
      if (inputRef.value && inputRef.value.focus) {
        inputRef.value.focus()
      }
    })
  } else {
    searchKeyword.value = ''
    selectedIndex.value = -1
  }
})
</script>

<style scoped>
.topbar-icon-btn {
  color: var(--text-color-regular);
  padding: 8px;
  border-radius: 10px;
  transition: all 0.25s ease;
}

.topbar-icon {
  color: currentColor;
  transition: transform 0.25s ease, color 0.25s ease;
}

.topbar-icon-btn:hover,
.topbar-icon-btn:focus-visible {
  color: var(--el-color-primary);
  background-color: color-mix(in srgb, var(--el-color-primary) 10%, transparent);
}

.topbar-icon-btn:hover .topbar-icon,
.topbar-icon-btn:focus-visible .topbar-icon {
  transform: scale(1.08);
}

.topbar-icon-btn:active {
  transform: scale(0.96);
}

.menu-search-trigger {
  display: inline-flex !important;
  align-items: center;
  justify-content: center;
  gap: 6px;
  height: 36px;
  padding: 0 10px !important;
  margin-inline-end: 4px;
  flex-shrink: 0;
}

.menu-search-kbd {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 0;
  padding: 1px 5px;
  border: 1px solid var(--el-border-color, #dcdfe6);
  border-radius: 6px;
  background: var(--el-fill-color-light, #f5f7fa);
  color: var(--el-text-color-secondary, #909399);
  font-size: 11px;
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  line-height: 1.4;
  white-space: nowrap;
}

@media (max-width: 1280px) {
  .menu-search-kbd {
    display: none;
  }

  .menu-search-trigger {
    padding: 8px !important;
    margin-inline-end: 0;
  }
}

.menu-search-content {
  padding: 8px;
}

.header-icon-fixed {
  display: flex;
  align-items: center;
  justify-content: center;
}

.menu-search-results {
  margin-top: 12px;
  max-height: 300px;
  overflow-y: auto;
}

.menu-search-item {
  display: flex;
  align-items: center;
  padding: 10px 12px;
  margin-bottom: 4px;
  border-radius: 4px;
  cursor: pointer;
  transition: background-color 0.2s;
  gap: 8px;
}

.menu-search-item:hover,
.menu-search-item.is-active {
  background-color: #f5f7fa;
}

.menu-item-icon {
  flex-shrink: 0;
  font-size: 16px;
  color: #606266;
}

.menu-item-title {
  flex: 1;
  font-size: 14px;
  color: #303133;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.menu-item-path {
  flex-shrink: 0;
  font-size: 12px;
  color: #909399;
  margin-left: 8px;
}

.menu-search-empty {
  margin-top: 12px;
  padding: 20px;
  text-align: center;
  color: #909399;
  font-size: 14px;
}

.menu-search-footer {
  margin-top: 8px;
  padding-top: 8px;
  border-top: 1px solid var(--el-border-color-lighter, #ebeef5);
  font-size: 12px;
  color: var(--el-text-color-secondary, #909399);
}
</style>

<style>
.menu-search-popover {
  padding: 0 !important;
}

.menu-search-popover .el-popover__content {
  padding: 0 !important;
}
</style>
