// html/src/views/tenant/TenantList.vue
<template>
  <div class="legacy-tenant-redirect">
    <el-result
      icon="info"
      :title="$t('platform.moved_title')"
      :sub-title="$t('platform.moved_hint')"
    >
      <template #extra>
        <el-button type="primary" @click="$router.push('/platform/tenants')">
          {{ $t('platform.go_platform') }}
        </el-button>
      </template>
    </el-result>
  </div>
</template>

<script setup>
// 租户管理已迁至平台控制台；保留此组件避免旧菜单 component 路径 404
</script>

// html-react/src/pages/tenant/TenantList.tsx
import { Button, Result } from 'antd'
import { useNavigate } from 'react-router-dom'
import { useTranslation } from 'react-i18next'

/** Legacy menu entry: tenant mgmt moved to platform console. */
export default function TenantList() {
  const { t } = useTranslation()
  const navigate = useNavigate()
  return (
    <Result
      status="info"
      title={t('platform.moved_title')}
      subTitle={t('platform.moved_hint')}
      extra={
        <Button type="primary" onClick={() => navigate('/platform/tenants')}>
          {t('platform.go_platform')}
        </Button>
      }
    />
  )
}
