// html-react/src/pages/log/SystemLogList.tsx
import { useEffect, useMemo, useState } from 'react'
import { App, Descriptions, Drawer, Space, Spin, Table, Tag, Tooltip } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { EyeOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  batchDeleteSystemLogs,
  cleanSystemLogs,
  deleteSystemLog,
  getSystemLogDetail,
  getSystemLogList,
  getSystemLogModuleOptions,
} from '@/api/log'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import LogCleanModal from './LogCleanModal'
import {
  createSystemLogSearchFields,
  extractLogDetail,
  formatSystemLogContext,
  formatSystemLogContextPreview,
  getSystemLogLevelColor,
  getSystemLogLevelLabel,
  getSystemLogModuleLabel,
  systemLogInitialSearchForm,
  transformSystemLogRow,
  type SystemLogRow,
} from './systemLog.config'

export default function SystemLogList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [selectedRowKeys, setSelectedRowKeys] = useState<Array<string | number>>([])
  const [detailOpen, setDetailOpen] = useState(false)
  const [detailLoading, setDetailLoading] = useState(false)
  const [logDetail, setLogDetail] = useState<SystemLogRow | null>(null)
  const [moduleOptions, setModuleOptions] = useState<Array<{ label: string; value: string }>>([])
  const [cleanOpen, setCleanOpen] = useState(false)
  const [cleanLoading, setCleanLoading] = useState(false)

  const getModuleLabel = (module?: string) => getSystemLogModuleLabel(t, module)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    refresh,
    handleSortChange,
  } = useListPage<SystemLogRow>({
    fetchApi: getSystemLogList,
    initialSearchForm: { ...systemLogInitialSearchForm },
    defaultSort: 'id:desc',
    transformData: (row) => transformSystemLogRow(row as unknown as Record<string, unknown>),
    onSearch: () => setSelectedRowKeys([]),
    onReset: () => setSelectedRowKeys([]),
  })

  const { toolbar, confirmDelete } = useCrudActions({
    onRefresh: refresh,
    deleteApi: deleteSystemLog,
  })

  useEffect(() => {
    void (async () => {
      try {
        const res = await getSystemLogModuleOptions()
        const data = res.data as Record<string, unknown> | undefined
        const modules = Array.isArray(data?.modules) ? (data.modules as string[]) : []
        setModuleOptions(
          modules.map((module) => ({
            label: getModuleLabel(module),
            value: module,
          })),
        )
      } catch {
        setModuleOptions([])
      }
    })()
  }, [t])

  const handleView = async (row: SystemLogRow) => {
    setDetailOpen(true)
    setDetailLoading(true)
    setLogDetail(null)
    try {
      const res = await getSystemLogDetail(row.id)
      const raw = extractLogDetail<Record<string, unknown>>(res.data as Record<string, unknown>, [
        'system_log',
        'log',
      ])
      if (raw) {
        setLogDetail(transformSystemLogRow(raw))
      }
    } catch (error) {
      showError(error, t('common.operation_failed'))
      setDetailOpen(false)
    } finally {
      setDetailLoading(false)
    }
  }

  const handleBatchDelete = () => {
    if (!selectedRowKeys.length) return
    modal.confirm({
      title: t('common.delete_confirm'),
      content: t('log.batch_delete_confirm', { count: selectedRowKeys.length }),
      okType: 'danger',
      onOk: async () => {
        try {
          await batchDeleteSystemLogs(selectedRowKeys)
          message.success(t('common.delete_success'))
          setSelectedRowKeys([])
          await refresh()
        } catch (error) {
          showError(error, t('common.operation_failed'))
        }
      },
    })
  }

  const handleClean = async (days: number) => {
    setCleanLoading(true)
    try {
      await cleanSystemLogs({ days })
      message.success(t('log.clean_success'))
      setCleanOpen(false)
      setSelectedRowKeys([])
      await refresh()
    } catch (error) {
      showError(error, t('common.operation_failed'))
    } finally {
      setCleanLoading(false)
    }
  }

  const searchFields = useMemo(
    () => createSystemLogSearchFields(t, moduleOptions),
    [t, moduleOptions],
  )

  const columns: ColumnsType<SystemLogRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    {
      title: t('log.level'),
      dataIndex: 'level',
      width: 100,
      render: (level: string) => (
        <Tag color={getSystemLogLevelColor(level)}>{getSystemLogLevelLabel(t, level)}</Tag>
      ),
    },
    {
      title: t('log.module'),
      dataIndex: 'module',
      width: 120,
      render: (module: string) => getModuleLabel(module),
    },
    {
      title: t('log.trace_id'),
      dataIndex: 'trace_id',
      width: 220,
      ellipsis: true,
      render: (traceId: string) => traceId || '-',
    },
    { title: t('log.message'), dataIndex: 'message', ellipsis: true },
    {
      title: t('log.context'),
      dataIndex: 'context',
      width: 200,
      ellipsis: true,
      render: (context: unknown) =>
        context ? (
          <Tooltip title={<pre style={{ margin: 0, maxWidth: 500, whiteSpace: 'pre-wrap' }}>{formatSystemLogContext(context)}</pre>}>
            <span style={{ cursor: 'pointer', color: '#1677ff' }}>{formatSystemLogContextPreview(context)}</span>
          </Tooltip>
        ) : (
          '-'
        ),
    },
    { title: t('log.time'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 160,
      fixed: 'end',
      onCell: () => ({ style: { whiteSpace: 'nowrap' } }),
      render: (_, row) => (
        <Space size={4} wrap={false}>
          {getButtonState('system_log.show').show ? (
            <PermissionButton
              permission="system_log.show"
              type="link"
              icon={<EyeOutlined />}
              onClick={() => void handleView(row)}
            >
              {t('common.view')}
            </PermissionButton>
          ) : null}
          {getButtonState('system_log.destroy').show ? (
            <PermissionButton
              permission="system_log.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, getModuleLabel(row.module))}
            >
              {t('common.delete')}
            </PermissionButton>
          ) : null}
        </Space>
      ),
    },
  ]

  return (
    <PageContainer
      title={t('menu.system_log')}
      extra={
        <Space>
          {selectedRowKeys.length > 0 && getButtonState('system_log.batch_delete').show ? (
            <PermissionButton permission="system_log.batch_delete" danger onClick={handleBatchDelete}>
              {t('common.delete_selected')} ({selectedRowKeys.length})
            </PermissionButton>
          ) : null}
          {getButtonState('system_log.clean').show ? (
            <PermissionButton permission="system_log.clean" onClick={() => setCleanOpen(true)}>
              {t('log.clean')}
            </PermissionButton>
          ) : null}
          {toolbar}
        </Space>
      }
    >
      <SearchForm
        fields={searchFields}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<SystemLogRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1300 }}
        rowSelection={
          getButtonState('system_log.batch_delete').show
            ? {
                selectedRowKeys,
                onChange: (keys) => setSelectedRowKeys(keys as Array<string | number>),
              }
            : undefined
        }
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager, _f, sorter) =>
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }
      />

      <Drawer open={detailOpen} title={t('log.detail')} width={1100} onClose={() => setDetailOpen(false)}>
        <Spin spinning={detailLoading}>
          {logDetail ? (
            <Descriptions bordered column={2} size="small">
              <Descriptions.Item label={t('table.id')}>{logDetail.id}</Descriptions.Item>
              <Descriptions.Item label={t('log.level')}>
                <Tag color={getSystemLogLevelColor(logDetail.level)}>
                  {getSystemLogLevelLabel(t, logDetail.level)}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label={t('log.module')}>{getModuleLabel(logDetail.module)}</Descriptions.Item>
              <Descriptions.Item label={t('log.trace_id')} span={2}>
                {logDetail.trace_id || '-'}
              </Descriptions.Item>
              <Descriptions.Item label={t('log.message')} span={2}>
                {logDetail.message}
              </Descriptions.Item>
              <Descriptions.Item label={t('log.context')} span={2}>
                {logDetail.context ? (
                  <pre style={{ margin: 0, maxHeight: 400, overflow: 'auto', fontSize: 12 }}>
                    {formatSystemLogContext(logDetail.context)}
                  </pre>
                ) : (
                  '-'
                )}
              </Descriptions.Item>
              <Descriptions.Item label={t('log.time')} span={2}>
                {logDetail.created_at}
              </Descriptions.Item>
            </Descriptions>
          ) : null}
        </Spin>
      </Drawer>

      <LogCleanModal
        open={cleanOpen}
        loading={cleanLoading}
        onClose={() => setCleanOpen(false)}
        onConfirm={handleClean}
      />
    </PageContainer>
  )
}

// html/src/views/log/SystemLogList.vue
<template>
  <div class="system-log-list">
    <ListPage
      ref="listPageRef"
      page-class="system-log"
      :title="$t('menu.system_log')"
      :show-add-button="false"
      :search-form="searchForm"
      :search-fields="searchFields"
      :initial-search-values="systemLogInitialSearchForm"
      i18n-prefix="log"
      :table-data="tableData"
      :loading="loading"
      :table-columns="tableColumns"
      :pagination="pagination"
      show-toolbar
      @search="handleSearch"
      @reset="handleReset"
      @refresh="loadData"
      @page-change="loadData"
      @sort-change="handleSortChange"
      @selection-change="onTableSelectionChange"
    >
      <template #toolbar-left>
        <el-button
          type="danger"
          :disabled="!selectedRows?.length || getButtonState('system_log.batch_delete').disabled"
          @click="handleBatchDelete"
        >
          <el-icon><Delete /></el-icon>
          {{ $t('common.delete_selected') }} ({{ selectedRows?.length || 0 }})
        </el-button>
        <el-button
          :disabled="!selectedRows?.length"
          @click="handleClearSelection"
        >
          {{ $t('common.reset') }}
        </el-button>
      </template>

      <template #level="{ row }">
        <el-tag :type="getSystemLogLevelType(row.level)">
          {{ getSystemLogLevelLabel(t, row.level) }}
        </el-tag>
      </template>

      <template #context="{ row }">
        <el-tooltip
          v-if="row.context"
          :content="formatSystemLogContext(row.context)"
          placement="top"
          effect="dark"
        >
          <div class="context-preview">
            {{ formatSystemLogContextPreview(row.context) }}
          </div>
        </el-tooltip>
        <span v-else>-</span>
      </template>

      <template #operation="{ row }">
        <TableActionButtons
          :row="row"
          :primary-actions="operationActions"
          :get-button-state="getButtonState"
        />
      </template>
    </ListPage>

    <el-dialog v-model="detailVisible" :title="$t('log.detail')" width="1100px">
      <el-descriptions v-if="logDetail" :column="2" border>
        <el-descriptions-item :label="$t('table.id')">{{ logDetail.id }}</el-descriptions-item>
        <el-descriptions-item :label="$t('log.level')">
          <el-tag :type="getSystemLogLevelType(logDetail.level)">
            {{ getSystemLogLevelLabel(t, logDetail.level) }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.module')">
          {{ getModuleLabel(logDetail.module) }}
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.trace_id')" :span="2">
          {{ logDetail.trace_id || '-' }}
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.message')" :span="2">
          {{ logDetail.message }}
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.context')" :span="2">
          <pre v-if="logDetail.context">{{ formatSystemLogContext(logDetail.context) }}</pre>
          <span v-else>-</span>
        </el-descriptions-item>
        <el-descriptions-item :label="$t('log.time')" :span="2">
          {{ logDetail.created_at }}
        </el-descriptions-item>
      </el-descriptions>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import { Delete } from '@element-plus/icons-vue'
import ListPage from '@/components/ListPage.vue'
import TableActionButtons from '@/components/TableActionButtons.vue'
import { useStandardListPage } from '@/composables/useStandardListPage'
import {
  getSystemLogList,
  getSystemLogModuleOptions,
  getSystemLogDetail,
  deleteSystemLog,
  batchDeleteSystemLogs
} from '@/api/log'
import {
  systemLogInitialSearchForm,
  transformSystemLogRow,
  createSystemLogSearchFields,
  createSystemLogTableColumns,
  getSystemLogLevelType,
  getSystemLogLevelLabel,
  getSystemLogModuleLabel,
  formatSystemLogContext,
  formatSystemLogContextPreview
} from './systemLog.config'

const { t, te } = useI18n()
const listPageRef = ref(null)
const detailVisible = ref(false)
const logDetail = ref(null)
const selectedRows = ref([])
const selectedIds = ref(new Set())
const moduleOptions = ref([])

const getTable = () => listPageRef.value?.tableRef?.tableRef

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  handleDelete: handleDeleteRow,
  handleBatchDelete: handleBatchDeleteRows,
  getButtonState
} = useStandardListPage({
  fetchApi: getSystemLogList,
  initialSearchForm: systemLogInitialSearchForm,
  defaultSort: 'id:desc',
  deleteApi: deleteSystemLog,
  batchDeleteApi: batchDeleteSystemLogs,
  transformData: transformSystemLogRow,
  tableRef: computed(() => getTable()),
  onSearch: () => {
    selectedRows.value = []
    selectedIds.value.clear()
  },
  onReset: () => {
    selectedRows.value = []
    selectedIds.value.clear()
  },
  onLoadSuccess: () => {
    nextTick(() => {
      const table = getTable()
      if (table && selectedIds.value.size > 0) {
        tableData.value
          .filter((row) => selectedIds.value.has(row.id))
          .forEach((row) => table.setCheckboxRow(row, true))
        selectedRows.value = table.getCheckboxRecords() || []
      }
    })
  }
})

const getModuleLabel = (module) => getSystemLogModuleLabel(t, te, module)
const searchFields = computed(() => createSystemLogSearchFields(t, moduleOptions.value))
const tableColumns = computed(() => createSystemLogTableColumns(t, getModuleLabel))

const loadModuleOptions = async () => {
  try {
    const res = await getSystemLogModuleOptions()
    const modules = Array.isArray(res?.data?.modules) ? res.data.modules : []
    moduleOptions.value = modules.map((module) => ({
      label: getModuleLabel(module),
      value: module
    }))
  } catch (error) {
    console.error('Load system log module options error:', error)
    moduleOptions.value = []
  }
}

const handleView = async (row) => {
  try {
    const res = await getSystemLogDetail(row.id)
    if (res?.data) {
      const log = res.data.system_log || res.data.log || res.data
      if (log) {
        logDetail.value = transformSystemLogRow(log)
        detailVisible.value = true
      }
    }
  } catch (error) {
    console.error('Load system log detail error:', error)
    ElMessage.error(error.response?.data?.message || error.message || t('error.default'))
  }
}

const handleDelete = (row) => handleDeleteRow(row, loadData)

const operationActions = computed(() => [
  {
    key: 'view',
    label: t('common.view'),
    type: 'primary',
    permission: 'system_log.show',
    handler: handleView
  },
  {
    key: 'delete',
    label: t('common.delete'),
    type: 'danger',
    permission: 'system_log.destroy',
    handler: handleDelete
  }
])

const onTableSelectionChange = () => {
  const table = getTable()
  if (!table) return

  const currentSelected = table.getCheckboxRecords() || []
  selectedRows.value = currentSelected

  tableData.value.forEach((row) => selectedIds.value.delete(row.id))
  currentSelected.forEach((row) => selectedIds.value.add(row.id))
}

const handleBatchDelete = () => {
  handleBatchDeleteRows(selectedRows.value, () => {
    selectedRows.value = []
    selectedIds.value.clear()
    loadData()
  })
}

const handleClearSelection = () => {
  selectedRows.value = []
  selectedIds.value.clear()
  const table = getTable()
  if (!table) return

  table.clearCheckboxRow?.()
  table.setAllCheckboxRow?.(false)
  table.clearCheckboxReserve?.()
  tableData.value.forEach((row) => table.setCheckboxRow?.(row, false))
}

onMounted(() => {
  loadModuleOptions()
})
</script>

<style scoped>
pre {
  margin: 0;
  padding: var(--space-sm);
  background: var(--bg-color-tertiary);
  border-radius: var(--border-radius-sm);
  overflow-x: auto;
  max-height: 400px;
  overflow-y: auto;
}

html.dark pre {
  background: var(--el-bg-color) !important;
  color: var(--el-text-color-regular) !important;
  border: 1px solid var(--el-border-color);
}

.context-preview {
  max-width: 200px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  cursor: pointer;
  color: var(--el-color-primary);
}
</style>
