// html/src/views/role/RoleList.vue
<template>
  <ListPage
    ref="listPageRef"
    page-class="role"
    :title="$t('menu.role')"
    :add-button-text="$t('role.add_role')"
    :add-button-disabled="getButtonState('role.store').disabled"
    :search-form="searchForm"
    :search-fields="searchFields"
    :initial-search-values="roleInitialSearchForm"
    i18n-prefix="role"
    :table-data="tableData"
    :loading="loading"
    :table-columns="tableColumns"
    :table-key="`table-${tableColumns.length}`"
    :pagination="pagination"
    show-toolbar
    show-column-setting
    :visible-columns="visibleColumns"
    :all-columns="allColumns"
    :default-visible-columns="defaultVisibleColumns"
    :column-order="columnOrder"
    :fixed-columns="fixedColumns"
    :on-column-setting-confirm="handleColumnSettingConfirm"
    @add="handleAdd"
    @search="handleSearch"
    @reset="handleReset"
    @refresh="loadData"
    @page-change="loadData"
    @sort-change="handleSortChange"
  >
    <template #status="{ row }">
      <el-switch
        :model-value="rowStatus(row) === 1"
        :disabled="isProtectedRole(row) || getButtonState('role.update').disabled"
        @change="(val) => handleStatusChange(row, val)"
      />
    </template>

    <template #operation="{ row }">
      <TableActionButtons
        :row="row"
        :primary-actions="getPrimaryActions(row)"
        :get-button-state="getButtonState"
      />
    </template>

    <template #form>
      <RoleForm
        ref="roleFormRef"
        v-model="dialogVisible"
        :edit-id="editId"
        @success="handleFormSuccess"
      />
    </template>
  </ListPage>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import ListPage from '@/components/ListPage.vue'
import TableActionButtons from '@/components/TableActionButtons.vue'
import RoleForm from './RoleForm.vue'
import { useStandardListPage } from '@/composables/useStandardListPage'
import { useColumnSetting } from '@/composables/useColumnSetting'
import { rowStatus } from '@/utils/listPageHelpers'
import { getRoleList, deleteRole, updateRole } from '@/api/role'
import {
  roleInitialSearchForm,
  createRoleSearchFields,
  createRoleTableColumns,
  isProtectedRole
} from './role.config'

const { t } = useI18n()
const listPageRef = ref(null)
const roleFormRef = ref(null)

const allTableColumns = computed(() => createRoleTableColumns(t))

const {
  tableColumns,
  visibleColumns,
  allColumns,
  defaultVisibleColumns,
  columnOrder,
  fixedColumns,
  handleColumnSettingConfirm
} = useColumnSetting('role', allTableColumns)

const searchFields = computed(() => createRoleSearchFields(t))

const {
  pagination,
  tableData,
  loading,
  searchForm,
  dialogVisible,
  editId,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  handleEdit,
  handleFormSuccess,
  handleDelete: handleDeleteRow,
  getButtonState
} = useStandardListPage({
  fetchApi: getRoleList,
  initialSearchForm: roleInitialSearchForm,
  defaultSort: 'id:desc',
  deleteApi: deleteRole,
  requireSensitiveConfirm: true,
  normalizeRows: false,
  tableRef: computed(() => listPageRef.value?.tableRef?.tableRef),
  beforeDelete: (row) => {
    if (isProtectedRole(row)) {
      ElMessage.warning(t('role.protected_cannot_delete'))
      return false
    }
  }
})

const handleAdd = () => {
  if (dialogVisible.value) {
    dialogVisible.value = false
    setTimeout(() => {
      editId.value = null
      dialogVisible.value = true
    }, 200)
  } else {
    editId.value = null
    dialogVisible.value = true
  }
}

const handleStatusChange = async (row, newStatus) => {
  if (isProtectedRole(row) && !newStatus) {
    ElMessage.warning(t('role.protected_cannot_disable'))
    loadData()
    return
  }

  try {
    const statusValue = newStatus ? 1 : 0
    await updateRole(row.id, { status: statusValue })
    ElMessage.success(newStatus ? t('role.enable_success') : t('role.disable_success'))
    const role = tableData.value.find((item) => item.id === row.id)
    if (role) {
      role.status = statusValue
    }
  } catch (error) {
    loadData()
    if (!error.__handled) {
      ElMessage.error(error.message || t('common.operation_failed'))
    }
  }
}

const handleDelete = (row) => handleDeleteRow(row, loadData)

const getPrimaryActions = (row) => [
  {
    key: 'edit',
    label: t('common.edit'),
    type: 'primary',
    permission: 'role.update',
    handler: handleEdit
  },
  {
    key: 'delete',
    label: t('common.delete'),
    type: 'danger',
    permission: 'role.destroy',
    show: () => !isProtectedRole(row),
    handler: handleDelete
  }
]
</script>

// html-react/src/pages/role/RoleList.tsx
import { useState } from 'react'
import { Button, Space, Table } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { SettingOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { deleteRole, getRoleList } from '@/api/role'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useColumnSetting } from '@/hooks/useColumnSetting'
import PageContainer from '@/components/PageContainer'
import ColumnSettingDialog from '@/components/ColumnSettingDialog'
import SearchForm from '@/components/SearchForm'
import StatusTag from '@/components/StatusTag'
import PermissionButton from '@/components/PermissionButton'
import RoleFormModal from './RoleFormModal'
import { roleInitialSearchForm, transformRoleRow, type RoleRow } from './role.config'

export default function RoleList() {
  const { t } = useTranslation()
  const { getButtonState } = usePermission()
  const [open, setOpen] = useState(false)
  const [editId, setEditId] = useState<string | number | null>(null)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<RoleRow, typeof roleInitialSearchForm>({
    fetchApi: getRoleList,
    initialSearchForm: roleInitialSearchForm,
    normalizeRows: true,
    transformData: transformRoleRow,
  })

  const { toolbar, confirmDelete } = useCrudActions({
    createPermission: 'role.store',
    onRefresh: refresh,
    onCreate: () => {
      setEditId(null)
      setOpen(true)
    },
    deleteApi: deleteRole,
    requireSensitiveConfirm: true,
  })

  const columns: ColumnsType<RoleRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('role.name'), dataIndex: 'name' },
    { title: t('role.slug'), dataIndex: 'slug' },
    { title: t('common.description'), dataIndex: 'description', ellipsis: true },
    { title: t('common.sort'), dataIndex: 'sort', width: 80, sorter: true },
    {
      title: t('common.status'),
      dataIndex: 'status',
      width: 100,
      render: (status: number) => <StatusTag status={status} />,
    },
    { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 160,
      fixed: 'end',
      render: (_, row) => (
        <Space>
          {getButtonState('role.update').show && (
            <PermissionButton
              permission="role.update"
              type="link"
              onClick={() => {
                setEditId(row.id)
                setOpen(true)
              }}
            >
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('role.destroy').show && row.slug !== 'super-admin' && (
            <PermissionButton
              permission="role.destroy"
              type="link"
              danger
              onClick={() => confirmDelete(row.id, row.name)}
            >
              {t('common.delete')}
            </PermissionButton>
          )}
        </Space>
      ),
    },
  ]

  const {
    filteredColumns,
    open: columnSettingOpen,
    openColumnSetting,
    closeColumnSetting,
    allColumns,
    visibleColumns,
    columnOrder,
    fixedColumns,
    handleConfirm: handleColumnSettingConfirm,
  } = useColumnSetting('role', columns)

  return (
    <PageContainer
      title={t('menu.role_management')}
      extra={
        <Space>
          {toolbar}
          <Button icon={<SettingOutlined />} onClick={openColumnSetting}>
            {t('common.column_setting')}
          </Button>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'name', label: t('role.name') },
          {
            name: 'status',
            label: t('common.status'),
            type: 'select',
            options: [
              { label: t('common.enabled'), value: 1 },
              { label: t('common.disabled'), value: 0 },
            ],
          },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<RoleRow>
        rowKey="id"
        loading={loading}
        columns={filteredColumns}
        dataSource={tableData}
        scroll={{ x: 1000 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager, _f, sorter) =>
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }
      />
      <RoleFormModal
        open={open}
        editId={editId}
        onClose={() => setOpen(false)}
        onSuccess={() => void refresh()}
      />
      <ColumnSettingDialog
        open={columnSettingOpen}
        onClose={closeColumnSetting}
        allColumns={allColumns}
        visibleColumns={visibleColumns}
        columnOrder={columnOrder}
        fixedColumns={fixedColumns}
        onConfirm={handleColumnSettingConfirm}
      />
    </PageContainer>
  )
}
