// html-react/src/pages/export/ImportList.tsx
import { useMemo, useState } from 'react'
import { App, Button, Space, Table, Tag } from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useTranslation } from 'react-i18next'
import { deleteImport, getImportList } from '@/api/import'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import { entityField } from '@/utils/normalize'
import { getApiBaseURL } from '@/utils/env'
import Storage from '@/utils/storage'
import i18n from '@/i18n'

interface ImportRow {
  id: number | string
  type?: string
  status?: number
  total_rows?: number
  success_rows?: number
  failed_rows?: number
  error_msg?: string
  error_file_url?: string
  created_at?: string
  admin?: Record<string, unknown> | null
}

function transformImportRow(row: Record<string, unknown>): ImportRow {
  const admin = (row.admin || row.Admin) as Record<string, unknown> | null
  return {
    id: entityField(row, 'id', '')!,
    type: String(entityField(row, 'type', '') ?? ''),
    status: Number(entityField(row, 'status', 0) ?? 0),
    total_rows: Number(entityField(row, 'total_rows', 0) ?? 0),
    success_rows: Number(entityField(row, 'success_rows', 0) ?? 0),
    failed_rows: Number(entityField(row, 'failed_rows', 0) ?? 0),
    error_msg: String(entityField(row, 'error_msg', '') ?? ''),
    error_file_url: String(entityField(row, 'error_file_url', '') ?? ''),
    created_at: String(entityField(row, 'created_at', '') ?? ''),
    admin,
  }
}

export default function ImportList() {
  const { t } = useTranslation()
  const { message } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [downloadingIds, setDownloadingIds] = useState<Set<string | number>>(new Set())

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<ImportRow>({
    fetchApi: getImportList,
    initialSearchForm: {
      type: '',
      status: '',
      start_time: '',
      end_time: '',
    },
    normalizeRows: false,
    transformData: (row) => transformImportRow(row as unknown as Record<string, unknown>),
  })

  const { confirmDelete } = useCrudActions({
    onRefresh: refresh,
    deleteApi: deleteImport,
  })

  const formatImportType = (type?: string) => {
    const map: Record<string, string> = {
      orders: t('menu.order'),
    }
    return map[type || ''] || type || '-'
  }

  const formatStatus = (status?: number) => {
    if (status === 1) return t('log.success')
    if (status === 0) return t('log.processing')
    return t('log.failed')
  }

  const getStatusColor = (status?: number) => {
    if (status === 1) return 'success'
    if (status === 0) return 'processing'
    return 'error'
  }

  const handleDownloadError = async (row: ImportRow) => {
    const importId = row.id
    if (downloadingIds.has(importId) || !row.error_file_url) return

    setDownloadingIds((prev) => new Set(prev).add(importId))
    try {
      let fullUrl = row.error_file_url
      if (fullUrl.startsWith('/')) {
        const apiBase = getApiBaseURL()
        const cleanUrl = fullUrl.replace(/^\/api\/admin/, '')
        fullUrl = `${apiBase.replace(/\/+$/, '')}${cleanUrl.startsWith('/') ? cleanUrl : `/${cleanUrl}`}`
      }

      const token = String(Storage.getItem('token', '') ?? '').trim()
      const currentLocale = i18n.language || Storage.getItem('language', 'zh-CN') || 'zh-CN'
      const acceptLanguage = currentLocale === 'en-US' ? 'en-US' : 'zh-CN'

      const response = await fetch(fullUrl, {
        method: 'GET',
        headers: {
          Authorization: `Bearer ${token}`,
          'Accept-Language': acceptLanguage,
        },
      })
      if (!response.ok) {
        throw new Error(`HTTP error! status: ${response.status}`)
      }

      const blob = await response.blob()
      const downloadUrl = window.URL.createObjectURL(blob)
      const link = document.createElement('a')
      link.href = downloadUrl
      link.download = `import_errors_${importId}.csv`
      link.style.display = 'none'
      document.body.appendChild(link)
      link.click()
      document.body.removeChild(link)
      window.URL.revokeObjectURL(downloadUrl)
      message.success(t('export.download_success'))
    } catch (error) {
      showError(error, t('export.download_failed'))
    } finally {
      setDownloadingIds((prev) => {
        const next = new Set(prev)
        next.delete(importId)
        return next
      })
    }
  }

  const columns = useMemo<ColumnsType<ImportRow>>(
    () => [
      { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
      { title: t('export.type'), dataIndex: 'type', width: 120, render: (v: string) => formatImportType(v) },
      {
        title: t('log.status'),
        dataIndex: 'status',
        width: 140,
        render: (status: number, row) => (
          <div>
            <Tag color={getStatusColor(status)}>{formatStatus(status)}</Tag>
            {status === 2 && row.error_msg ? (
              <div style={{ marginTop: 4, color: '#ff4d4f', fontSize: 12, wordBreak: 'break-all' }}>{row.error_msg}</div>
            ) : null}
          </div>
        ),
      },
      { title: t('import.total_rows'), dataIndex: 'total_rows', width: 100 },
      { title: t('import.success_rows'), dataIndex: 'success_rows', width: 100 },
      { title: t('import.failed_rows'), dataIndex: 'failed_rows', width: 100 },
      {
        title: t('log.admin'),
        dataIndex: 'admin',
        width: 140,
        render: (admin: Record<string, unknown> | null) =>
          String(entityField(admin || {}, 'username', '-') ?? '-'),
      },
      { title: t('table.created_at'), dataIndex: 'created_at', width: 180, sorter: true },
      {
        title: t('common.operation'),
        key: 'operation',
        width: 200,
        fixed: 'end',
        render: (_, row) => (
          <Space>
            {row.error_file_url ? (
              <Button
                type="link"
                loading={downloadingIds.has(row.id)}
                onClick={() => void handleDownloadError(row)}
              >
                {t('import.download_error')}
              </Button>
            ) : null}
            {getButtonState('import.destroy').show ? (
              <PermissionButton
                permission="import.destroy"
                type="link"
                danger
                onClick={() => confirmDelete(row.id)}
              >
                {t('common.delete')}
              </PermissionButton>
            ) : null}
          </Space>
        ),
      },
    ],
    [confirmDelete, downloadingIds, getButtonState, t],
  )

  return (
    <div>
      <SearchForm
        fields={[
          {
            name: 'type',
            label: t('export.type'),
            type: 'select',
            options: [{ label: t('menu.order'), value: 'orders' }],
          },
          {
            name: 'status',
            label: t('log.status'),
            type: 'select',
            options: [
              { label: t('log.processing'), value: '0' },
              { label: t('log.success'), value: '1' },
              { label: t('log.failed'), value: '2' },
            ],
          },
          { name: 'start_time', label: t('log.start_time') },
          { name: 'end_time', label: t('log.end_time') },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />
      <Table<ImportRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1200 }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager, _f, sorter) =>
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }
      />
    </div>
  )
}

// html/src/views/export/ImportList.vue
<template>
  <ListPage
    ref="listPageRef"
    page-class="import"
    :title="embedded ? '' : $t('export.tab_imports')"
    :show-add-button="false"
    :search-form="searchForm"
    :search-fields="searchFields"
    :initial-search-values="initialSearchForm"
    :table-data="tableData"
    :loading="loading"
    :table-columns="tableColumns"
    :pagination="pagination"
    show-toolbar
    @search="handleSearch"
    @reset="handleReset"
    @refresh="loadData"
    @page-change="loadData"
    @sort-change="handleSortChange"
  >
    <template #status="{ row }">
      <div>
        <el-tag :type="statusTagType(row.status)">
          {{ formatStatus(row.status) }}
        </el-tag>
        <div
          v-if="Number(row.status) === 2 && row.error_msg"
          style="margin-top: 4px; color: #f56c6c; font-size: 12px; word-break: break-all;"
        >
          {{ row.error_msg }}
        </div>
      </div>
    </template>

    <template #operation="{ row }">
      <el-button
        v-if="row.error_file_url"
        type="primary"
        link
        :loading="downloadingIds.has(row.id)"
        @click="handleDownloadError(row)"
      >
        {{ $t('import.download_error') }}
      </el-button>
      <el-button
        type="danger"
        link
        :disabled="getButtonState('import.destroy').disabled"
        @click="handleDelete(row)"
      >
        {{ $t('common.delete') }}
      </el-button>
    </template>
  </ListPage>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { ElMessage } from 'element-plus'
import ListPage from '@/components/ListPage.vue'
import { useStandardListPage } from '@/composables/useStandardListPage'
import { getImportList, deleteImport } from '@/api/import'
import Storage from '@/utils/storage'

defineProps({
  embedded: { type: Boolean, default: true }
})

const { t, locale } = useI18n()
const listPageRef = ref(null)
const downloadingIds = ref(new Set())

const initialSearchForm = {
  type: '',
  status: '',
  start_time: '',
  end_time: ''
}

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch,
  handleReset,
  handleSortChange,
  handleDelete,
  getButtonState
} = useStandardListPage({
  fetchApi: getImportList,
  initialSearchForm,
  defaultSort: 'id:desc',
  deleteApi: deleteImport,
  normalizeRows: false,
  transformData: (row) => ({
    id: row.id,
    type: row.type || '',
    status: Number(row.status ?? 0),
    total_rows: Number(row.total_rows ?? 0),
    success_rows: Number(row.success_rows ?? 0),
    failed_rows: Number(row.failed_rows ?? 0),
    error_msg: row.error_msg || '',
    error_file_url: row.error_file_url || '',
    created_at: row.created_at || '',
    admin: row.admin || row.Admin || null
  }),
  tableRef: computed(() => listPageRef.value?.tableRef?.tableRef)
})

const searchFields = computed(() => [
  {
    prop: 'type',
    label: t('export.type'),
    type: 'select',
    options: [{ label: t('menu.order'), value: 'orders' }]
  },
  {
    prop: 'status',
    label: t('log.status'),
    type: 'select',
    options: [
      { label: t('log.processing'), value: '0' },
      { label: t('log.success'), value: '1' },
      { label: t('log.failed'), value: '2' }
    ]
  },
  { prop: 'start_time', label: t('log.start_time'), type: 'datetime' },
  { prop: 'end_time', label: t('log.end_time'), type: 'datetime' }
])

const tableColumns = computed(() => [
  { prop: 'id', label: t('table.id'), width: 80, sortable: 'custom' },
  {
    prop: 'type',
    label: t('export.type'),
    width: 120,
    formatter: ({ cellValue }) => (cellValue === 'orders' ? t('menu.order') : cellValue || '-')
  },
  { prop: 'status', label: t('log.status'), width: 140, slot: 'status' },
  { prop: 'total_rows', label: t('import.total_rows'), width: 100 },
  { prop: 'success_rows', label: t('import.success_rows'), width: 100 },
  { prop: 'failed_rows', label: t('import.failed_rows'), width: 100 },
  {
    prop: 'admin',
    label: t('log.admin'),
    width: 140,
    formatter: ({ cellValue }) => cellValue?.username || cellValue?.Username || '-'
  },
  { prop: 'created_at', label: t('table.created_at'), width: 180, sortable: 'custom' },
  { prop: 'operation', label: t('common.operation'), width: 200, slot: 'operation', fixed: 'right' }
])

const formatStatus = (status) => {
  if (Number(status) === 1) return t('log.success')
  if (Number(status) === 0) return t('log.processing')
  return t('log.failed')
}

const statusTagType = (status) => {
  if (Number(status) === 1) return 'success'
  if (Number(status) === 0) return 'warning'
  return 'danger'
}

const handleDownloadError = async (row) => {
  if (!row.error_file_url || downloadingIds.value.has(row.id)) return
  downloadingIds.value.add(row.id)
  try {
    let fullUrl = row.error_file_url
    if (fullUrl.startsWith('/')) {
      const apiBaseURL = import.meta.env.VITE_API_BASE_URL
      const apiPrefix = import.meta.env.VITE_API_PREFIX || '/api/admin'
      if (apiBaseURL) {
        const cleanUrl = fullUrl.replace(/^\/api\/admin/, '')
        fullUrl = `${apiBaseURL.replace(/\/+$/, '')}${apiPrefix.replace(/\/+$/, '')}${cleanUrl}`
      }
    }
    const token = Storage.getItem('token') || ''
    const acceptLanguage = locale.value === 'en-US' ? 'en-US' : 'zh-CN'
    const response = await fetch(fullUrl, {
      method: 'GET',
      headers: {
        Authorization: `Bearer ${token}`,
        'Accept-Language': acceptLanguage
      }
    })
    if (!response.ok) throw new Error(`HTTP ${response.status}`)
    const blob = await response.blob()
    const url = window.URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `import_errors_${row.id}.csv`
    link.click()
    window.URL.revokeObjectURL(url)
    ElMessage.success(t('export.download_success'))
  } catch (e) {
    ElMessage.error(t('export.download_failed'))
  } finally {
    downloadingIds.value.delete(row.id)
  }
}
</script>
