// html-react/src/pages/order/OrderList.tsx
import { useMemo, useState } from 'react'
import {
  App,
  Descriptions,
  Divider,
  Drawer,
  Form,
  Input,
  Modal,
  Select,
  Space,
  Table,
  Tag,
  Upload,
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import type { UploadProps } from 'antd/es/upload'
import { UploadOutlined } from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import {
  deleteOrder,
  exportOrder,
  getOrderDetail,
  getOrderList,
  importOrder,
  updateOrder,
} from '@/api/order'
import { useListPage } from '@/hooks/useListPage'
import { handlePaginatedTableChange } from '@/utils/tableChange'
import { useCrudActions } from '@/hooks/useCrudActions'
import { usePermission } from '@/hooks/usePermission'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { useQueuedExport } from '@/hooks/useQueuedExport'
import PageContainer from '@/components/PageContainer'
import SearchForm from '@/components/SearchForm'
import PermissionButton from '@/components/PermissionButton'
import { entityField } from '@/utils/normalize'
import OrderFormModal from './OrderFormModal'
import {
  createOrderInitialSearchForm,
  formatOrderAmount,
  formatOrderTime,
  getOrderDetailField,
  getOrderDetails,
  getOrderStatusTagColor,
  getOrderStatusText,
  ORDER_STATUS_OPTIONS,
  type OrderSearchForm,
} from './order.config'

interface OrderRow {
  id: number | string
  order_no?: string
  user_id?: number | string
  amount?: number | string
  status?: string
  remark?: string
  expire_at?: string | null
  created_at?: string
  details?: Record<string, unknown>[]
  name?: string
}

interface OrderDetailPayload {
  order?: Record<string, unknown>
  details?: Record<string, unknown>[]
}

const initialSearch = createOrderInitialSearchForm()

export default function OrderList() {
  const { t } = useTranslation()
  const { message, modal } = App.useApp()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const [editForm] = Form.useForm()

  const [createOpen, setCreateOpen] = useState(false)
  const [detailOpen, setDetailOpen] = useState(false)
  const [orderDetail, setOrderDetail] = useState<OrderDetailPayload | null>(null)
  const [editOpen, setEditOpen] = useState(false)
  const [editSubmitting, setEditSubmitting] = useState(false)
  const [currentEditOrder, setCurrentEditOrder] = useState<Record<string, unknown> | null>(null)
  const [importing, setImporting] = useState(false)

  const {
    tableData,
    loading,
    pagination,
    searchForm,
    onSearchFormChange,
    loadData,
    handleSearch,
    handleReset,
    handleSortChange,
    refresh,
  } = useListPage<OrderRow, OrderSearchForm>({
    fetchApi: getOrderList,
    initialSearchForm: initialSearch,
    defaultSort: 'created_at:desc',
    normalizeRows: true,
    transformData: (row) => {
      const record = row
      return {
        id: entityField(record, 'id', '')!,
        order_no: String(entityField(record, 'order_no', '') ?? ''),
        user_id: entityField(record, 'user_id', '') as number | string,
        amount: entityField(record, 'amount', 0) as number | string,
        status: String(entityField(record, 'status', '') ?? ''),
        remark: String(entityField(record, 'remark', '') ?? ''),
        expire_at: (entityField(record, 'expire_at', null) as string | null) || null,
        created_at: String(entityField(record, 'created_at', '') ?? ''),
        details: getOrderDetails(record),
        name: String(entityField(record, 'order_no', '') ?? ''),
      }
    },
  })

  const { toolbar } = useCrudActions({
    createPermission: 'order.store',
    onRefresh: refresh,
    onCreate: () => setCreateOpen(true),
  })

  const { exporting, handleExport } = useQueuedExport({
    exportApi: exportOrder,
    getParams: () => ({ ...searchForm }),
    redirectPath: '/exports',
  })

  const statusOptions = useMemo(
    () =>
      ORDER_STATUS_OPTIONS.map((item) => ({
        label: t(item.labelKey),
        value: item.value,
      })),
    [t],
  )

  const openDetail = async (row: OrderRow) => {
    try {
      const orderNo = row.order_no
      const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
      setOrderDetail((res.data || {}) as OrderDetailPayload)
      setDetailOpen(true)
    } catch (error) {
      showError(error, t('common.query_failed'))
    }
  }

  const openEdit = async (row: OrderRow) => {
    try {
      const orderNo = row.order_no
      const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
      const data = (res.data || {}) as OrderDetailPayload
      if (!data.order) {
        message.error(t('common.query_failed'))
        return
      }
      setCurrentEditOrder(data.order)
      editForm.setFieldsValue({
        status: String(getOrderDetailField(data.order, 'status', 'pending')),
        remark: String(getOrderDetailField(data.order, 'remark', '') || ''),
      })
      setEditOpen(true)
    } catch (error) {
      showError(error, t('common.query_failed'))
    }
  }

  const closeEdit = () => {
    setEditOpen(false)
    setCurrentEditOrder(null)
    editForm.resetFields()
  }

  const handleEditSubmit = async () => {
    if (!currentEditOrder) return
    try {
      const values = await editForm.validateFields()
      setEditSubmitting(true)
      const orderNo = String(getOrderDetailField(currentEditOrder, 'order_no', '') || '')
      const id = getOrderDetailField(currentEditOrder, 'id', '') as string | number
      await updateOrder(id, {
        status: values.status,
        remark: values.remark || '',
        order_no: orderNo,
      })
      message.success(t('common.update_success'))
      closeEdit()
      await refresh()
    } catch (error) {
      if ((error as { errorFields?: unknown })?.errorFields) return
      showError(error, t('common.operation_failed'))
    } finally {
      setEditSubmitting(false)
    }
  }

  const handleDelete = (row: OrderRow) => {
    modal.confirm({
      title: t('common.delete_confirm'),
      content: row.order_no || undefined,
      okType: 'danger',
      onOk: async () => {
        try {
          await deleteOrder(row.id, row.order_no ? { order_no: row.order_no } : {})
          message.success(t('common.delete_success'))
          await refresh()
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        }
      },
    })
  }

  const uploadProps: UploadProps = {
    accept: '.csv',
    showUploadList: false,
    beforeUpload: (file) => {
      if (!file.name.toLowerCase().endsWith('.csv')) {
        message.error(t('common.invalid_file_type'))
        return false
      }
      setImporting(true)
      void importOrder(file as File)
        .then((res) => {
          const payload = (res.data || {}) as Record<string, unknown>
          const result = ((payload.data || payload) as Record<string, unknown>) || {}
          if (result.async && result.import_id) {
            message.success(t('export.task_submitted'))
            return
          }
          const successCount = Number(result.success_count || 0)
          const failedCount = Number(result.failed_count || 0)
          const errors = Array.isArray(result.errors) ? (result.errors as string[]) : []

          if (successCount > 0) {
            message.success(t('common.import_success'))
            if (failedCount > 0 && errors.length) {
              message.warning(errors.slice(0, 10).join('\n'))
            }
            void refresh()
          } else {
            message.warning(t('common.import_no_data'))
            if (errors.length) {
              message.error(errors.slice(0, 10).join('\n'))
            }
          }
        })
        .catch((error) => showError(error, t('common.operation_failed')))
        .finally(() => setImporting(false))
      return false
    },
  }

  const detailColumns: ColumnsType<Record<string, unknown>> = [
    {
      title: t('order.product_name'),
      dataIndex: 'product_name',
      width: 200,
      render: (_, detail) => String(entityField(detail, 'product_name', '-') ?? '-'),
    },
    {
      title: t('order.price'),
      dataIndex: 'price',
      width: 120,
      render: (_, detail) => formatOrderAmount(entityField(detail, 'price')),
    },
    {
      title: t('order.quantity'),
      dataIndex: 'quantity',
      width: 100,
      render: (_, detail) => Number(entityField(detail, 'quantity', 0) ?? 0),
    },
    {
      title: t('order.subtotal'),
      dataIndex: 'subtotal',
      width: 120,
      render: (_, detail) => formatOrderAmount(entityField(detail, 'subtotal')),
    },
  ]

  const columns: ColumnsType<OrderRow> = [
    { title: t('table.id'), dataIndex: 'id', width: 80, sorter: true },
    { title: t('order.order_no'), dataIndex: 'order_no' },
    { title: t('order.user_id'), dataIndex: 'user_id', width: 100 },
    {
      title: t('order.amount'),
      dataIndex: 'amount',
      width: 120,
      sorter: true,
      render: (v) => formatOrderAmount(v),
    },
    {
      title: t('order.status'),
      dataIndex: 'status',
      width: 110,
      render: (status: string) => (
        <Tag color={getOrderStatusTagColor(status)}>{getOrderStatusText(t, status)}</Tag>
      ),
    },
    {
      title: t('order.created_at'),
      dataIndex: 'created_at',
      width: 180,
      sorter: true,
    },
    {
      title: t('order.expire_at'),
      dataIndex: 'expire_at',
      width: 180,
      render: (v: string | null | undefined) => formatOrderTime(v) || '-',
    },
    {
      title: t('order.remark'),
      dataIndex: 'remark',
      width: 160,
      ellipsis: true,
      render: (v) => v || '-',
    },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 220,
      fixed: 'end',
      render: (_, row) => (
        <Space>
          {getButtonState('order.show').show && (
            <PermissionButton permission="order.show" type="link" onClick={() => void openDetail(row)}>
              {t('common.view')}
            </PermissionButton>
          )}
          {getButtonState('order.update').show && (
            <PermissionButton permission="order.update" type="link" onClick={() => void openEdit(row)}>
              {t('common.edit')}
            </PermissionButton>
          )}
          {getButtonState('order.destroy').show && (
            <PermissionButton permission="order.destroy" type="link" danger onClick={() => handleDelete(row)}>
              {t('common.delete')}
            </PermissionButton>
          )}
        </Space>
      ),
    },
  ]

  const orderInfo = orderDetail?.order

  return (
    <PageContainer
      title={t('menu.order')}
      extra={
        <Space wrap>
          {toolbar}
          <Upload {...uploadProps}>
            <PermissionButton permission="order.import" icon={<UploadOutlined />} loading={importing}>
              {t('common.import')}
            </PermissionButton>
          </Upload>
          <PermissionButton
            permission="order.export"
            type="primary"
            loading={exporting}
            onClick={() => void handleExport()}
          >
            {t('common.export')}
          </PermissionButton>
        </Space>
      }
    >
      <SearchForm
        fields={[
          { name: 'user_id', label: t('order.user_id') },
          { name: 'order_no', label: t('order.order_no') },
          {
            name: 'status',
            label: t('order.status'),
            type: 'select',
            options: statusOptions,
          },
          { name: 'min_amount', label: t('order.min_amount'), advanced: true },
          { name: 'max_amount', label: t('order.max_amount'), advanced: true },
          { name: 'start_time', label: t('order.start_time'), type: 'datetime', advanced: true },
          { name: 'end_time', label: t('order.end_time'), type: 'datetime', advanced: true },
        ]}
        values={searchForm}
        onChange={onSearchFormChange}
        onSearch={handleSearch}
        onReset={handleReset}
      />

      <Table<OrderRow>
        rowKey="id"
        loading={loading}
        columns={columns}
        dataSource={tableData}
        scroll={{ x: 1380 }}
        expandable={{
          expandedRowRender: (row) => (
            <div style={{ padding: '8px 12px' }}>
              <h4 style={{ margin: '0 0 8px' }}>{t('order.order_details')}</h4>
              <Table
                size="small"
                pagination={false}
                rowKey={(_, index) => String(index)}
                columns={detailColumns}
                dataSource={row.details || []}
              />
            </div>
          ),
        }}
        pagination={{
          current: pagination.page,
          pageSize: pagination.pageSize,
          total: pagination.total,
          showSizeChanger: true,
          showTotal: (total) => t('common.total', { total }),
        }}
        onChange={(pager, _f, sorter) =>
          handlePaginatedTableChange({ pager, sorter, pagination, loadData, handleSortChange })
        }
      />

      <OrderFormModal open={createOpen} onClose={() => setCreateOpen(false)} onSuccess={() => void refresh()} />

      <Modal
        open={editOpen}
        title={t('order.edit_order')}
        width={600}
        destroyOnHidden
        confirmLoading={editSubmitting}
        onCancel={closeEdit}
        onOk={() => void handleEditSubmit()}
        okText={t('common.confirm')}
        cancelText={t('common.cancel')}
      >
        <Form form={editForm} layout="vertical">
          <Form.Item
            name="status"
            label={t('order.status')}
            rules={[{ required: true, message: t('order.status_required') }]}
          >
            <Select placeholder={t('order.update_status_tip')} options={statusOptions} />
          </Form.Item>
          <Form.Item name="remark" label={t('order.remark')}>
            <Input.TextArea rows={4} placeholder={t('order.remark_placeholder')} />
          </Form.Item>
        </Form>
      </Modal>

      <Drawer open={detailOpen} title={t('order.detail')} width="80%" onClose={() => setDetailOpen(false)}>
        {orderInfo ? (
          <>
            <Descriptions column={2} bordered size="small">
              <Descriptions.Item label={t('order.order_no')}>
                {String(getOrderDetailField(orderInfo, 'order_no'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.user_id')}>
                {String(getOrderDetailField(orderInfo, 'user_id'))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.amount')}>
                {formatOrderAmount(getOrderDetailField(orderInfo, 'amount', 0))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.status')}>
                <Tag color={getOrderStatusTagColor(String(getOrderDetailField(orderInfo, 'status', '')))}>
                  {getOrderStatusText(t, String(getOrderDetailField(orderInfo, 'status', '')))}
                </Tag>
              </Descriptions.Item>
              <Descriptions.Item label={t('order.created_at')}>
                {formatOrderTime(getOrderDetailField(orderInfo, 'created_at', ''))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.expire_at')}>
                {formatOrderTime(getOrderDetailField(orderInfo, 'expire_at', ''))}
              </Descriptions.Item>
              <Descriptions.Item label={t('order.remark')} span={2}>
                {String(getOrderDetailField(orderInfo, 'remark') || '-')}
              </Descriptions.Item>
            </Descriptions>
            <Divider>{t('order.details')}</Divider>
            <Table
              size="small"
              pagination={false}
              rowKey={(_, index) => String(index)}
              columns={detailColumns}
              dataSource={orderDetail?.details || []}
            />
          </>
        ) : null}
      </Drawer>
    </PageContainer>
  )
}

// html/src/views/order/OrderList.vue
<template>
  <div class="order-list">
    <ListPage
      ref="listPageRef"
      page-class="order"
      :title="$t('menu.order')"
      :add-button-text="$t('order.add_order')"
      :add-button-disabled="getButtonState('order.store').disabled"
      :search-form="searchForm"
      :search-fields="searchFields"
      :initial-search-values="orderInitialSearchForm"
      i18n-prefix="order"
      :table-data="tableData"
      :loading="loading"
      :table-columns="tableColumns"
      :pagination="pagination"
      :hide-total-threshold="100000"
      show-toolbar
      @add="handleAdd"
      @search="handleSearch"
      @reset="handleReset"
      @refresh="loadData"
      @page-change="loadData"
    >
      <template #user_id="{ model, field }">
        <el-input v-model="model[field.prop]" :placeholder="t('order.user_id')" />
      </template>

      <template #extra-buttons>
        <el-button
          type="primary"
          :disabled="getButtonState('order.import').disabled || isImporting"
          :loading="isImporting"
          @click="handleImport"
        >
          <el-icon><Upload /></el-icon>
          {{ $t('common.import') }}
        </el-button>
        <el-button
          type="success"
          :disabled="getButtonState('order.export').disabled || isExporting"
          :loading="isExporting"
          @click="handleExport"
        >
          {{ $t('common.export') }}
        </el-button>
      </template>

      <template #table>
        <vxe-table
          ref="tableRef"
          :data="tableData"
          :loading="loading"
          border
          :size="vxeSize"
          :column-config="{ resizable: true }"
          height="600"
          :sort-config="{ multiple: false, trigger: 'default' }"
          @sort-change="handleSortChange"
        >
          <vxe-column type="expand" width="60">
            <template #content="{ row }">
              <div class="order-details-expand">
                <h4>{{ t('order.order_details') }}</h4>
                <vxe-table
                  :data="getOrderDetails(row)"
                  border
                  :size="vxeSize"
                  :show-header="true"
                >
                  <vxe-column field="product_name" :title="t('order.product_name')" width="200">
                    <template #default="{ row: detail }">
                      {{ detail.product_name || detail.ProductName || '-' }}
                    </template>
                  </vxe-column>
                  <vxe-column field="price" :title="t('order.price')" width="120">
                    <template #default="{ row: detail }">
                      {{ formatOrderAmount(detail.price || detail.Price) }}
                    </template>
                  </vxe-column>
                  <vxe-column field="quantity" :title="t('order.quantity')" width="100">
                    <template #default="{ row: detail }">
                      {{ detail.quantity || detail.Quantity || 0 }}
                    </template>
                  </vxe-column>
                  <vxe-column field="subtotal" :title="t('order.subtotal')" width="120">
                    <template #default="{ row: detail }">
                      {{ formatOrderAmount(detail.subtotal || detail.Subtotal) }}
                    </template>
                  </vxe-column>
                </vxe-table>
              </div>
            </template>
          </vxe-column>
          <template v-for="(column, index) in tableColumns">
            <vxe-column
              v-if="column.type"
              :key="`type-${column.type}-${index}`"
              :type="column.type"
              :width="column.width"
              :fixed="column.fixed"
            />
            <vxe-column
              v-else
              :key="column.field || column.slot || index"
              :field="column.field"
              :title="column.title"
              :width="column.width"
              :sortable="column.sortable"
              :fixed="column.fixed"
              :formatter="column.formatter"
            >
              <template v-if="column.slot === 'status'" #default="{ row }">
                <el-tag :type="getOrderStatusTagType(row.status)">
                  {{ getOrderStatusText(t, row.status) }}
                </el-tag>
              </template>
              <template v-else-if="column.slot === 'amount'" #default="{ row }">
                {{ formatOrderAmount(row.amount) }}
              </template>
              <template v-else-if="column.slot === 'operation'" #default="{ row }">
                <TableActionButtons
                  :row="row"
                  :primary-actions="getPrimaryActions(row)"
                  :get-button-state="getButtonState"
                  @action="handleAction"
                />
              </template>
            </vxe-column>
          </template>
        </vxe-table>
      </template>

      <template #form>
        <OrderForm v-model="dialogVisible" @success="handleFormSuccess" />
      </template>
    </ListPage>

    <input
      ref="fileInputRef"
      type="file"
      accept=".csv"
      style="display: none"
      @change="handleFileChange"
    />

    <el-dialog
      v-model="editDialogVisible"
      :title="$t('order.edit_order')"
      width="600px"
      :close-on-click-modal="false"
      @close="handleEditDialogClose"
    >
      <el-form
        ref="editFormRef"
        :model="editFormData"
        :rules="editFormRules"
        label-width="120px"
      >
        <el-form-item :label="$t('order.status')" prop="status">
          <el-select v-model="editFormData.status" :placeholder="$t('order.update_status_tip')" style="width: 100%">
            <el-option :label="$t('order.status_pending')" value="pending" />
            <el-option :label="$t('order.status_paid')" value="paid" />
            <el-option :label="$t('order.status_cancelled')" value="cancelled" />
          </el-select>
        </el-form-item>
        <el-form-item :label="$t('order.remark')" prop="remark">
          <el-input
            v-model="editFormData.remark"
            type="textarea"
            :rows="4"
            :placeholder="$t('order.remark_placeholder')"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="handleEditDialogClose">{{ $t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="editSubmitting" @click="handleEditSubmit">
          {{ $t('common.confirm') }}
        </el-button>
      </template>
    </el-dialog>

    <el-dialog
      v-model="detailDialogVisible"
      :title="$t('order.detail')"
      width="80%"
      :close-on-click-modal="false"
    >
      <div v-if="orderDetail" class="order-detail">
        <el-descriptions :column="2" border>
          <el-descriptions-item :label="$t('order.order_no')">
            {{ getOrderDetailField(orderDetail.order, 'order_no') }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.user_id')">
            {{ getOrderDetailField(orderDetail.order, 'user_id') }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.amount')">
            {{ formatOrderAmount(getOrderDetailField(orderDetail.order, 'amount', 0)) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.status')">
            <el-tag :type="getOrderStatusTagType(orderDetail.order?.status)">
              {{ getOrderStatusText(t, orderDetail.order?.status) }}
            </el-tag>
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.created_at')">
            {{ formatOrderTime(orderDetail.order?.created_at) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.expire_at')">
            {{ formatOrderTime(orderDetail.order?.expire_at) }}
          </el-descriptions-item>
          <el-descriptions-item :label="$t('order.remark')">
            {{ getOrderDetailField(orderDetail.order, 'remark') }}
          </el-descriptions-item>
        </el-descriptions>

        <el-divider>{{ $t('order.details') }}</el-divider>

        <vxe-table :data="orderDetail.details || []" border :size="vxeSize">
          <vxe-column field="product_name" :title="$t('order.product_name')" />
          <vxe-column
            field="price"
            :title="$t('order.price')"
            :formatter="({ row }) => formatOrderAmount(row.price)"
          />
          <vxe-column field="quantity" :title="$t('order.quantity')" />
          <vxe-column
            field="subtotal"
            :title="$t('order.subtotal')"
            :formatter="({ row }) => formatOrderAmount(row.subtotal)"
          />
        </vxe-table>
      </div>
    </el-dialog>
  </div>
</template>

<script setup>
import { ref, reactive, watch, onMounted, computed, nextTick } from 'vue'
import { useI18n } from 'vue-i18n'
import { useQueuedExport } from '@/composables/useQueuedExport'
import { useCsvImport } from '@/composables/useCsvImport'
import { ElMessage, ElMessageBox } from 'element-plus'
import { Upload } from '@element-plus/icons-vue'
import ListPage from '@/components/ListPage.vue'
import TableActionButtons from '@/components/TableActionButtons.vue'
import OrderForm from './OrderForm.vue'
import { useListPage } from '@/composables/useListPage'
import { usePermission } from '@/composables/usePermission'
import { useCrud } from '@/composables/useCrud'
import { useVxeTableSize } from '@/composables/useVxeTableSize'
import {
  getOrderList,
  getOrderDetail,
  updateOrder,
  deleteOrder,
  exportOrder,
  importOrder
} from '@/api/order'
import logger from '@/utils/logger'
import ErrorHandler from '@/utils/errorHandler'
import { validateTimeRange, ORDER_MAX_TIME_RANGE_MONTHS } from '@/utils/timeRangeValidator'
import {
  createOrderInitialSearchForm,
  createOrderSearchFields,
  createOrderTableColumns,
  formatOrderAmount,
  formatOrderTime,
  getOrderStatusText,
  getOrderStatusTagType,
  getOrderDetailField,
  getOrderDetails
} from './order.config'

const { getButtonState } = usePermission()
const { vxeSize } = useVxeTableSize()
const { t } = useI18n()
const listPageRef = ref(null)
const tableRef = ref(null)
const orderInitialSearchForm = createOrderInitialSearchForm()

const { dialogVisible, handleFormSuccess: handleFormSuccessCrud } = useCrud()
const detailDialogVisible = ref(false)
const orderDetail = ref(null)
const editDialogVisible = ref(false)
const editFormRef = ref(null)
const editSubmitting = ref(false)
const currentEditOrder = ref(null)
const editFormData = reactive({ status: '', remark: '' })

const editFormRules = computed(() => ({
  status: [{ required: true, message: t('order.status_required'), trigger: 'change' }]
}))

const {
  pagination,
  tableData,
  loading,
  searchForm,
  loadData,
  handleSearch: handleSearchBase,
  handleReset,
  handleSortChange,
  initDefaultSort
} = useListPage({
  fetchApi: getOrderList,
  initialSearchForm: orderInitialSearchForm,
  defaultSort: 'created_at:desc',
  normalizeRows: false,
  tableRef: computed(() => tableRef.value)
})

const searchFields = computed(() => createOrderSearchFields(t))
const tableColumns = computed(() => createOrderTableColumns(t))

const { isExporting, handleExport } = useQueuedExport({
  exportApi: exportOrder,
  getParams: () => searchForm
})

const { fileInputRef, isImporting, handleImport, handleFileChange } = useCsvImport({
  importApi: importOrder,
  onSuccess: loadData
})

const getCurrentTimeString = () => {
  const now = new Date()
  const pad = (n) => String(n).padStart(2, '0')
  return `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())} ${pad(now.getHours())}:${pad(now.getMinutes())}:${pad(now.getSeconds())}`
}

const validateTimeRangeForSearch = () => {
  if (!searchForm.start_time) return true
  const endTime = searchForm.end_time || getCurrentTimeString()
  const validation = validateTimeRange(searchForm.start_time, endTime, ORDER_MAX_TIME_RANGE_MONTHS)
  if (!validation.valid) {
    let errorMessage = validation.error
    if (validation.errorKey) {
      const translationKey = `order.${validation.errorKey}`
      errorMessage = validation.errorParams
        ? t(translationKey, validation.errorParams)
        : t(translationKey)
    }
    ElMessage.warning(errorMessage)
    return false
  }
  return true
}

const isInitialized = ref(false)
watch(
  () => [searchForm.start_time, searchForm.end_time],
  ([newStartTime, newEndTime], [oldStartTime, oldEndTime]) => {
    if (!isInitialized.value) {
      isInitialized.value = true
      return
    }
    if (newStartTime !== oldStartTime || newEndTime !== oldEndTime) {
      if (newStartTime) {
        const endTime = newEndTime || getCurrentTimeString()
        const validation = validateTimeRange(newStartTime, endTime, ORDER_MAX_TIME_RANGE_MONTHS)
        if (!validation.valid) {
          let errorMessage = validation.error
          if (validation.errorKey) {
            const translationKey = `order.${validation.errorKey}`
            errorMessage = validation.errorParams
              ? t(translationKey, validation.errorParams)
              : t(translationKey)
          }
          ElMessage.warning(errorMessage)
        }
      }
    }
  }
)

const handleSearch = () => {
  if (!validateTimeRangeForSearch()) return
  handleSearchBase()
}

const handleView = async (row) => {
  try {
    const orderNo = row.order_no
    const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
    if (res.data) {
      orderDetail.value = res.data
      detailDialogVisible.value = true
    }
  } catch (error) {
    logger.error('View order detail error:', error)
    ErrorHandler.handle(error, { silent: true })
  }
}

const handleEdit = async (row) => {
  try {
    const orderNo = row.order_no
    const res = await getOrderDetail(row.id, orderNo ? { order_no: orderNo } : {})
    if (res.data?.order) {
      currentEditOrder.value = res.data.order
      editFormData.status = res.data.order.status || 'pending'
      editFormData.remark = res.data.order.remark || ''
      editDialogVisible.value = true
    }
  } catch (error) {
    logger.error('Get order detail for edit error:', error)
    ErrorHandler.handle(error, { silent: true })
  }
}

const handleEditDialogClose = () => {
  editDialogVisible.value = false
  currentEditOrder.value = null
  editFormData.status = ''
  editFormData.remark = ''
  editFormRef.value?.resetFields()
  editFormRef.value?.clearValidate()
}

const handleEditSubmit = async () => {
  if (!editFormRef.value) return
  try {
    await editFormRef.value.validate()
  } catch {
    return
  }
  if (!currentEditOrder.value) return

  editSubmitting.value = true
  try {
    const orderNo = currentEditOrder.value.order_no
    await updateOrder(currentEditOrder.value.id, {
      status: editFormData.status,
      remark: editFormData.remark || '',
      order_no: orderNo
    })
    ElMessage.success(t('common.update_success'))
    handleEditDialogClose()
    loadData()
  } catch (error) {
    logger.error('Update order error:', error)
    ErrorHandler.handle(error, { silent: true })
  } finally {
    editSubmitting.value = false
  }
}

const handleDelete = async (row) => {
  try {
    await ElMessageBox.confirm(t('common.delete_confirm'), t('form.tip'), {
      confirmButtonText: t('common.confirm'),
      cancelButtonText: t('common.cancel'),
      type: 'warning'
    })
    const orderNo = row.order_no
    await deleteOrder(row.id, orderNo ? { order_no: orderNo } : {})
    ElMessage.success(t('common.delete_success'))
    loadData()
  } catch (error) {
    if (error !== 'cancel') {
      logger.error('Delete order error:', error)
      ErrorHandler.handle(error, { silent: true })
    }
  }
}

const getPrimaryActions = () => [
  { key: 'view', label: t('common.view'), type: 'info', permission: 'order.show', handler: handleView },
  { key: 'edit', label: t('common.edit'), type: 'primary', permission: 'order.update', handler: handleEdit },
  { key: 'delete', label: t('common.delete'), type: 'danger', permission: 'order.destroy', handler: handleDelete }
]

const handleAction = (command, row) => {
  if (command === 'view') handleView(row)
  if (command === 'edit') handleEdit(row)
  if (command === 'delete') handleDelete(row)
}

const handleAdd = () => {
  dialogVisible.value = true
}

const handleFormSuccess = () => {
  handleFormSuccessCrud(loadData)
}

onMounted(async () => {
  try {
    await loadData()
    await nextTick()
    initDefaultSort()
  } catch (error) {
    logger.error('OrderList onMounted error:', error)
    ErrorHandler.handle(error)
  }
})
</script>

<style scoped>
.order-details-expand {
  padding: var(--space-sm);
  background-color: var(--bg-color-tertiary);
}

.order-details-expand h4 {
  margin: var(--space-sm) 0;
  font-weight: bold;
  color: var(--text-color-primary);
}

html.dark .order-details-expand {
  background-color: var(--el-bg-color) !important;
}

html.dark .order-details-expand h4 {
  color: var(--el-text-color-primary) !important;
}

.order-detail {
  padding: 20px 0;
}
</style>
