// html/src/components/SlideCaptcha.vue
﻿<template>
  <div class="slide-captcha">
    <GoCaptchaSlide :config="config" :data="slideData" :events="events" />
  </div>
</template>

<script setup>
/**
 * Puzzle slider captcha (go-captcha). The answer is only verified server-side on login.
 * Re-mount with a new :key (captcha_id) to reset after a refresh.
 */
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { Slide as GoCaptchaSlide } from 'go-captcha-vue'
import 'go-captcha-vue/dist/style.css'

const props = defineProps({
  // Payload of GET /login/captcha when type=slide
  data: { type: Object, required: true }
})
const emit = defineEmits(['confirm', 'refresh'])

const { t } = useI18n()

const config = computed(() => ({
  // Background size returned by the API; the slide answer uses these coordinates.
  width: props.data.master_width || 300,
  height: props.data.master_height || 220,
  title: t('login.slide_title'),
  showTheme: true
}))

const slideData = computed(() => ({
  image: props.data.master_image,
  thumb: props.data.tile_image,
  thumbX: props.data.tile_x,
  thumbY: props.data.tile_y,
  thumbWidth: props.data.tile_width,
  thumbHeight: props.data.tile_height
}))

const events = {
  confirm: (point) => {
    emit('confirm', String(Math.round(point.x)))
  },
  refresh: () => {
    emit('refresh')
  }
}
</script>

<style scoped>
.slide-captcha {
  display: flex;
  justify-content: center;
  width: 100%;
  margin-bottom: 8px;
}
</style>

// html-react/src/components/SlideCaptcha.tsx
﻿import { memo, useMemo } from 'react'
import GoCaptcha from 'go-captcha-react'
import { useTranslation } from 'react-i18next'

/** Slide captcha payload returned by GET /login/captcha when type=slide. */
export interface SlideCaptchaData {
  captcha_id: string
  master_image: string
  tile_image: string
  /** Background size returned by the API; the slide answer uses these coordinates. */
  master_width?: number
  master_height?: number
  tile_width: number
  tile_height: number
  tile_x: number
  tile_y: number
}

interface SlideCaptchaProps {
  data: SlideCaptchaData
  /** Called with the x offset ("123") after the user releases the slider. */
  onConfirm: (answer: string) => void
  /** Called when the user clicks the built-in refresh icon. */
  onRefresh: () => void
}

/**
 * Puzzle slider captcha (go-captcha). The answer is only verified server-side on login.
 * Remount with a new `key` (captcha_id) to reset after a refresh.
 */
function SlideCaptcha({ data, onConfirm, onRefresh }: SlideCaptchaProps) {
  const { t } = useTranslation()

  const config = useMemo(
    () => ({
      width: data.master_width || 300,
      height: data.master_height || 220,
      title: t('login.slide_title'),
      showTheme: true,
    }),
    [t, data.master_width, data.master_height],
  )

  const slideData = useMemo(
    () => ({
      image: data.master_image,
      thumb: data.tile_image,
      thumbX: data.tile_x,
      thumbY: data.tile_y,
      thumbWidth: data.tile_width,
      thumbHeight: data.tile_height,
    }),
    [data],
  )

  const events = useMemo(
    () => ({
      confirm: (point: { x: number; y: number }) => {
        onConfirm(String(Math.round(point.x)))
      },
      refresh: onRefresh,
    }),
    [onConfirm, onRefresh],
  )

  return (
    <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 16 }}>
      <GoCaptcha.Slide config={config} data={slideData} events={events} />
    </div>
  )
}

export default memo(SlideCaptcha)
