// html/src/views/schedule/FlexibleSchedulesPanel.vue
<template>
  <el-card shadow="never" class="flexible-card">
    <template #header>
      <div class="flexible-card__header">
        <h3 class="flexible-card__title">{{ t('schedule.flexible_title') }}</h3>
        <el-button :loading="loading" @click="loadData">{{ t('common.refresh') }}</el-button>
      </div>
    </template>

    <el-table v-loading="loading" :data="rows" row-key="id" border>
      <el-table-column prop="name" :label="t('schedule.flexible_name')" min-width="120" />
      <el-table-column :label="t('schedule.flexible_handler')" min-width="160">
        <template #default="{ row }">
          <div>{{ row.handler_name || row.handler }}</div>
          <code class="muted">{{ row.handler }}</code>
        </template>
      </el-table-column>
      <el-table-column :label="t('schedule.cron')" min-width="200">
        <template #default="{ row }">
          <code>{{ row.cron_expr || '-' }}</code>
          <div v-if="row.cron_expr" class="muted">{{ describeCron(row.cron_expr, t) }}</div>
        </template>
      </el-table-column>
      <el-table-column :label="t('common.status')" width="90" align="center">
        <template #default="{ row }">
          <el-switch
            :model-value="row.enabled"
            :disabled="getButtonState('flexible_schedule.update').disabled"
            @change="(v) => onToggle(row, v)"
          />
        </template>
      </el-table-column>
      <el-table-column :label="t('schedule.last_status')" width="100" align="center">
        <template #default="{ row }">
          <el-tag :type="statusTagType(row.last_status)" size="small">
            {{ statusLabel(row.last_status) }}
          </el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="last_run_at" :label="t('schedule.last_run_at')" min-width="150">
        <template #default="{ row }">{{ formatDateTimeDisplay(row.last_run_at) }}</template>
      </el-table-column>
      <el-table-column :label="t('schedule.last_duration')" width="100" align="right">
        <template #default="{ row }">{{ formatDuration(row.last_duration_ms) }}</template>
      </el-table-column>
      <el-table-column :label="t('schedule.flexible_next_runs')" min-width="170">
        <template #default="{ row }">
          <div v-if="row.next_runs?.length" class="muted">
            <div v-for="r in row.next_runs.slice(0, 2)" :key="r">{{ formatDateTimeDisplay(r) }}</div>
          </div>
          <span v-else>-</span>
        </template>
      </el-table-column>
      <el-table-column :label="t('common.operation')" width="240" fixed="right" align="center">
        <template #default="{ row }">
          <el-button
            type="primary"
            link
            :disabled="getButtonState('flexible_schedule.update').disabled"
            @click="openEdit(row)"
          >
            {{ t('common.edit') }}
          </el-button>
          <el-button
            type="primary"
            link
            :loading="runningId === row.id"
            :disabled="getButtonState('flexible_schedule.run').disabled"
            @click="onRun(row)"
          >
            {{ t('schedule.run_now') }}
          </el-button>
          <el-button
            link
            :disabled="!row.last_status || row.last_status === 'never'"
            @click="openResult(row)"
          >
            {{ t('schedule.view_result') }}
          </el-button>
        </template>
      </el-table-column>
    </el-table>

    <el-dialog v-model="formVisible" :title="t('common.edit')" width="520px">
      <el-form :model="form" label-width="100px">
        <el-form-item :label="t('schedule.cron')" required>
          <el-input v-model="form.cron_expr" placeholder="*/5 * * * *" />
          <div class="muted">{{ t('schedule.flexible_cron_tip') }}</div>
        </el-form-item>
        <el-form-item :label="t('common.status')">
          <el-switch v-model="form.enabled" />
        </el-form-item>
        <el-form-item>
          <el-button @click="onPreview">{{ t('schedule.flexible_preview') }}</el-button>
        </el-form-item>
        <el-form-item v-if="previewRuns.length" :label="t('schedule.flexible_next_runs')">
          <div class="muted">
            <div v-for="r in previewRuns" :key="r">{{ formatDateTimeDisplay(r) }}</div>
          </div>
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="formVisible = false">{{ t('common.cancel') }}</el-button>
        <el-button type="primary" :loading="saving" @click="onSave">{{ t('common.confirm') }}</el-button>
      </template>
    </el-dialog>

    <el-dialog v-model="resultVisible" :title="t('schedule.result_title')" width="720px">
      <el-descriptions :column="1" border>
        <el-descriptions-item :label="t('schedule.flexible_name')">
          {{ resultData.name || '-' }}
        </el-descriptions-item>
        <el-descriptions-item :label="t('schedule.flexible_handler')">
          {{ resultData.handler_name || resultData.handler || '-' }}
        </el-descriptions-item>
        <el-descriptions-item :label="t('schedule.last_status')">
          <el-tag :type="statusTagType(resultData.last_status)" size="small">
            {{ statusLabel(resultData.last_status) }}
          </el-tag>
        </el-descriptions-item>
        <el-descriptions-item :label="t('schedule.last_run_at')">
          {{ resultData.last_run_at || '-' }}
        </el-descriptions-item>
        <el-descriptions-item :label="t('schedule.last_duration')">
          {{ formatDuration(resultData.last_duration_ms) }}
        </el-descriptions-item>
        <el-descriptions-item v-if="resultData.last_error" :label="t('schedule.error')">
          <pre class="schedule-result-pre schedule-result-pre--error">{{ resultData.last_error }}</pre>
        </el-descriptions-item>
        <el-descriptions-item :label="t('schedule.output')">
          <pre class="schedule-result-pre">{{ resultData.last_output || t('schedule.output_empty') }}</pre>
        </el-descriptions-item>
      </el-descriptions>
      <template #footer>
        <el-button type="primary" @click="resultVisible = false">{{ t('common.close') }}</el-button>
      </template>
    </el-dialog>
  </el-card>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { useI18n } from 'vue-i18n'
import {
  getFlexibleScheduleList,
  previewFlexibleSchedule,
  runFlexibleSchedule,
  updateFlexibleSchedule,
} from '@/api/schedule'
import { usePermission } from '@/composables/usePermission'
import { describeCron } from '@/utils/cronLabel'
import { formatDateTimeDisplay } from '@/utils/dateUtils'
import { logger } from '@/utils/logger'

const { t } = useI18n()
const { getButtonState } = usePermission()

const loading = ref(false)
const saving = ref(false)
const rows = ref([])
const runningId = ref(null)
const formVisible = ref(false)
const editing = ref(null)
const previewRuns = ref([])
const resultVisible = ref(false)
const resultData = reactive({
  name: '',
  handler: '',
  handler_name: '',
  last_status: '',
  last_run_at: '',
  last_duration_ms: undefined,
  last_error: '',
  last_output: '',
})
const form = reactive({
  cron_expr: '*/5 * * * *',
  enabled: true,
})

function statusLabel(status) {
  if (status === 'success') return t('schedule.status_success')
  if (status === 'failed') return t('schedule.status_failed')
  if (status === 'skipped') return t('schedule.flexible_status_skipped')
  return t('schedule.status_never')
}

function statusTagType(status) {
  if (status === 'success') return 'success'
  if (status === 'failed') return 'danger'
  if (status === 'skipped') return 'warning'
  return 'info'
}

function formatDuration(ms) {
  if (ms === undefined || ms === null || ms === '') return '-'
  if (ms < 1000) return `${ms} ms`
  return `${(ms / 1000).toFixed(2)} s`
}

function openResult(row = {}) {
  resultData.name = row.name || ''
  resultData.handler = row.handler || ''
  resultData.handler_name = row.handler_name || ''
  resultData.last_status = row.last_status || ''
  resultData.last_run_at = row.last_run_at || ''
  resultData.last_duration_ms = row.last_duration_ms
  resultData.last_error = row.last_error || ''
  resultData.last_output = row.last_output || ''
  resultVisible.value = true
}

async function loadData() {
  loading.value = true
  try {
    const listRes = await getFlexibleScheduleList()
    rows.value = listRes.data?.list || []
  } catch (error) {
    logger.error('Failed to load flexible schedules:', error)
  } finally {
    loading.value = false
  }
}

function openEdit(row) {
  editing.value = row
  Object.assign(form, {
    cron_expr: row.cron_expr,
    enabled: !!row.enabled,
  })
  previewRuns.value = row.next_runs || []
  formVisible.value = true
}

async function onPreview() {
  try {
    const res = await previewFlexibleSchedule({
      cron_expr: form.cron_expr,
      count: 5,
    })
    previewRuns.value = res.data?.next_runs || []
  } catch (error) {
    logger.error('preview failed', error)
  }
}

async function onSave() {
  if (!editing.value) return
  saving.value = true
  try {
    await updateFlexibleSchedule(editing.value.id, {
      cron_expr: form.cron_expr,
      enabled: !!form.enabled,
    })
    ElMessage.success(t('common.update_success'))
    formVisible.value = false
    await loadData()
  } catch (error) {
    logger.error('save flexible schedule failed', error)
  } finally {
    saving.value = false
  }
}

async function onToggle(row, enabled) {
  try {
    await updateFlexibleSchedule(row.id, { enabled })
    ElMessage.success(t('common.update_success'))
    await loadData()
  } catch (error) {
    logger.error('toggle failed', error)
  }
}

async function onRun(row) {
  try {
    await ElMessageBox.confirm(
      t('schedule.flexible_run_confirm', { name: row.name || row.handler }),
      t('schedule.run_now'),
      { type: 'warning' },
    )
  } catch {
    return
  }
  runningId.value = row.id
  try {
    const res = await runFlexibleSchedule(row.id, !row.enabled)
    const updated = res.data?.flexible_schedule
    if (updated?.last_status === 'failed') {
      ElMessage.warning(t('schedule.run_failed'))
    } else if (updated?.last_status === 'skipped') {
      ElMessage.warning(t('schedule.flexible_status_skipped'))
    } else {
      ElMessage.success(t('schedule.run_success'))
    }
    await loadData()
    if (updated) openResult(updated)
  } catch (error) {
    logger.error('run failed', error)
  } finally {
    runningId.value = null
  }
}

onMounted(loadData)
</script>

<style scoped>
.flexible-card {
  margin-top: 16px;
}
.flexible-card__header {
  display: flex;
  justify-content: space-between;
  gap: 12px;
  align-items: center;
}
.flexible-card__title {
  margin: 0;
  font-size: 16px;
  font-weight: 600;
}
.muted {
  color: var(--el-text-color-secondary);
  font-size: 12px;
  line-height: 1.4;
}
.schedule-result-pre {
  margin: 0;
  max-height: 320px;
  overflow: auto;
  white-space: pre-wrap;
  word-break: break-word;
  font-size: 12px;
  line-height: 1.6;
  font-family: Consolas, 'Courier New', ui-monospace, SFMono-Regular, Menlo, Monaco, monospace;
}
.schedule-result-pre--error {
  max-height: 160px;
  color: var(--el-color-danger);
}
</style>

// html-react/src/pages/schedule/FlexibleSchedulesPanel.tsx
import { useEffect, useState } from 'react'
import {
  App,
  Button,
  Card,
  Descriptions,
  Form,
  Input,
  Modal,
  Space,
  Switch,
  Table,
  Tag,
  theme,
} from 'antd'
import type { ColumnsType } from 'antd/es/table'
import { useTranslation } from 'react-i18next'
import {
  getFlexibleScheduleList,
  previewFlexibleSchedule,
  runFlexibleSchedule,
  updateFlexibleSchedule,
  type FlexibleScheduleRow,
} from '@/api/schedule'
import PermissionButton from '@/components/PermissionButton'
import { useUnhandledError } from '@/hooks/useUnhandledError'
import { usePermission } from '@/hooks/usePermission'
import { describeCron } from '@/utils/cronLabel'
import { formatDateTimeDisplay } from '@/utils/dateUtils'
import { logger } from '@/utils/logger'

function formatDuration(ms?: number) {
  if (ms === undefined || ms === null) return '-'
  if (ms < 1000) return `${ms} ms`
  return `${(ms / 1000).toFixed(2)} s`
}

export default function FlexibleSchedulesPanel() {
  const { t } = useTranslation()
  const { modal, message } = App.useApp()
  const { token } = theme.useToken()
  const showError = useUnhandledError()
  const { getButtonState } = usePermission()
  const canUpdate = !getButtonState('flexible_schedule.update').disabled
  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<FlexibleScheduleRow[]>([])
  const [runningId, setRunningId] = useState<number | null>(null)
  const [formOpen, setFormOpen] = useState(false)
  const [editing, setEditing] = useState<FlexibleScheduleRow | null>(null)
  const [saving, setSaving] = useState(false)
  const [previewRuns, setPreviewRuns] = useState<string[]>([])
  const [resultOpen, setResultOpen] = useState(false)
  const [resultRow, setResultRow] = useState<FlexibleScheduleRow | null>(null)
  const [form] = Form.useForm()

  const mutedTextStyle = {
    color: token.colorTextSecondary,
    fontSize: 12,
    lineHeight: 1.4,
  } as const

  const statusLabel = (status?: string) => {
    if (status === 'success') return t('schedule.status_success')
    if (status === 'failed') return t('schedule.status_failed')
    if (status === 'skipped') return t('schedule.flexible_status_skipped')
    return t('schedule.status_never')
  }

  const statusColor = (status?: string) => {
    if (status === 'success') return 'success'
    if (status === 'failed') return 'error'
    if (status === 'skipped') return 'warning'
    return 'default'
  }

  const loadData = async () => {
    setLoading(true)
    try {
      const listRes = await getFlexibleScheduleList()
      setRows(listRes.data?.list || [])
    } catch (error) {
      logger.error('Failed to load flexible schedules:', error)
      showError(error, t('common.query_failed'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    void loadData()
  }, [])

  const openEdit = (row: FlexibleScheduleRow) => {
    setEditing(row)
    form.setFieldsValue({
      cron_expr: row.cron_expr,
      enabled: row.enabled,
    })
    setPreviewRuns(row.next_runs || [])
    setFormOpen(true)
  }

  const onPreview = async () => {
    try {
      const values = await form.validateFields(['cron_expr'])
      const res = await previewFlexibleSchedule({
        cron_expr: values.cron_expr,
        count: 5,
      })
      setPreviewRuns(res.data?.next_runs || [])
    } catch (error) {
      if (error && typeof error === 'object' && 'errorFields' in error) return
      showError(error, t('common.operation_failed'))
    }
  }

  const onSave = async () => {
    if (!editing) return
    try {
      const values = await form.validateFields()
      setSaving(true)
      await updateFlexibleSchedule(editing.id, {
        cron_expr: values.cron_expr,
        enabled: !!values.enabled,
      })
      message.success(t('common.update_success'))
      setFormOpen(false)
      await loadData()
    } catch (error) {
      if (error && typeof error === 'object' && 'errorFields' in error) return
      showError(error, t('common.operation_failed'))
    } finally {
      setSaving(false)
    }
  }

  const onToggle = async (row: FlexibleScheduleRow, enabled: boolean) => {
    try {
      await updateFlexibleSchedule(row.id, { enabled })
      message.success(t('common.update_success'))
      await loadData()
    } catch (error) {
      showError(error, t('common.operation_failed'))
    }
  }

  const openResult = (row: FlexibleScheduleRow) => {
    setResultRow(row)
    setResultOpen(true)
  }

  const onRun = (row: FlexibleScheduleRow) => {
    modal.confirm({
      title: t('schedule.run_now'),
      content: t('schedule.flexible_run_confirm', { name: row.name || row.handler }),
      onOk: async () => {
        setRunningId(row.id)
        try {
          const res = await runFlexibleSchedule(row.id, !row.enabled)
          const updated = res.data?.flexible_schedule
          if (updated?.last_status === 'failed') {
            message.warning(t('schedule.run_failed'))
          } else if (updated?.last_status === 'skipped') {
            message.warning(t('schedule.flexible_status_skipped'))
          } else {
            message.success(t('schedule.run_success'))
          }
          await loadData()
          if (updated) openResult(updated)
        } catch (error) {
          showError(error, t('common.operation_failed'))
          throw error
        } finally {
          setRunningId(null)
        }
      },
    })
  }

  const columns: ColumnsType<FlexibleScheduleRow> = [
    {
      title: t('schedule.flexible_name'),
      dataIndex: 'name',
      key: 'name',
      minWidth: 140,
    },
    {
      title: t('schedule.flexible_handler'),
      key: 'handler',
      minWidth: 160,
      render: (_, row) => (
        <div>
          <div>{row.handler_name || row.handler}</div>
          <code style={{ fontSize: 12, color: token.colorTextSecondary }}>{row.handler}</code>
        </div>
      ),
    },
    {
      title: t('schedule.cron'),
      dataIndex: 'cron_expr',
      key: 'cron_expr',
      minWidth: 200,
      render: (value?: string) => (
        <div>
          <code style={{ fontFamily: "Consolas, 'Courier New', monospace", fontSize: 12 }}>
            {value || '-'}
          </code>
          {value ? (
            <div style={{ marginTop: 4, ...mutedTextStyle }}>{describeCron(value, t)}</div>
          ) : null}
        </div>
      ),
    },
    {
      title: t('common.status'),
      dataIndex: 'enabled',
      key: 'enabled',
      width: 100,
      align: 'center',
      render: (enabled: boolean, row) => (
        <Switch checked={enabled} onChange={(v) => void onToggle(row, v)} disabled={!canUpdate} />
      ),
    },
    {
      title: t('schedule.last_status'),
      dataIndex: 'last_status',
      key: 'last_status',
      width: 100,
      align: 'center',
      render: (value?: string) => <Tag color={statusColor(value)}>{statusLabel(value)}</Tag>,
    },
    {
      title: t('schedule.last_run_at'),
      dataIndex: 'last_run_at',
      key: 'last_run_at',
      minWidth: 160,
      render: (v?: string) => formatDateTimeDisplay(v),
    },
    {
      title: t('schedule.last_duration'),
      dataIndex: 'last_duration_ms',
      key: 'last_duration_ms',
      width: 100,
      align: 'right',
      render: (v?: number) => formatDuration(v),
    },
    {
      title: t('schedule.flexible_next_runs'),
      dataIndex: 'next_runs',
      key: 'next_runs',
      minWidth: 180,
      render: (runs?: string[]) =>
        runs && runs.length ? (
          <div style={{ fontSize: 12, lineHeight: 1.5 }}>
            {runs.slice(0, 2).map((r) => (
              <div key={r}>{formatDateTimeDisplay(r)}</div>
            ))}
          </div>
        ) : (
          '-'
        ),
    },
    {
      title: t('common.operation'),
      key: 'operation',
      width: 240,
      fixed: 'right',
      align: 'center',
      render: (_, row) => (
        <Space size={0}>
          <PermissionButton permission="flexible_schedule.update" type="link" onClick={() => openEdit(row)}>
            {t('common.edit')}
          </PermissionButton>
          <PermissionButton
            permission="flexible_schedule.run"
            type="link"
            loading={runningId === row.id}
            onClick={() => onRun(row)}
          >
            {t('schedule.run_now')}
          </PermissionButton>
          <Button
            type="link"
            disabled={!row.last_status || row.last_status === 'never'}
            onClick={() => openResult(row)}
          >
            {t('schedule.view_result')}
          </Button>
        </Space>
      ),
    },
  ]

  return (
    <>
      <Card
        style={{ marginTop: 16 }}
        title={t('schedule.flexible_title')}
        extra={
          <Button onClick={() => void loadData()} loading={loading}>
            {t('common.refresh')}
          </Button>
        }
      >
        <Table
          rowKey="id"
          loading={loading}
          columns={columns}
          dataSource={rows}
          scroll={{ x: 1200 }}
          pagination={false}
        />
      </Card>

      <Modal
        title={t('common.edit')}
        open={formOpen}
        onCancel={() => setFormOpen(false)}
        onOk={() => void onSave()}
        confirmLoading={saving}
        destroyOnClose
        width={560}
      >
        <Form form={form} layout="vertical" style={{ marginTop: 12 }}>
          <Form.Item
            name="cron_expr"
            label={t('schedule.cron')}
            extra={t('schedule.flexible_cron_tip')}
            rules={[{ required: true }]}
          >
            <Input placeholder="*/5 * * * *" />
          </Form.Item>
          <Form.Item name="enabled" label={t('common.status')} valuePropName="checked">
            <Switch />
          </Form.Item>
          <Space style={{ marginBottom: 12 }}>
            <Button onClick={() => void onPreview()}>{t('schedule.flexible_preview')}</Button>
          </Space>
          {previewRuns.length > 0 ? (
            <div style={{ marginBottom: 8, fontSize: 12, color: token.colorTextSecondary }}>
              <div>{t('schedule.flexible_next_runs')}:</div>
              {previewRuns.map((r) => (
                <div key={r}>{formatDateTimeDisplay(r)}</div>
              ))}
            </div>
          ) : null}
        </Form>
      </Modal>

      <Modal
        open={resultOpen}
        title={t('schedule.result_title')}
        onCancel={() => setResultOpen(false)}
        footer={[
          <Button key="close" type="primary" onClick={() => setResultOpen(false)}>
            {t('common.close')}
          </Button>,
        ]}
        width={720}
        destroyOnClose
      >
        <Descriptions column={1} bordered size="small">
          <Descriptions.Item label={t('schedule.flexible_name')}>
            {resultRow?.name || '-'}
          </Descriptions.Item>
          <Descriptions.Item label={t('schedule.flexible_handler')}>
            {resultRow?.handler_name || resultRow?.handler || '-'}
          </Descriptions.Item>
          <Descriptions.Item label={t('schedule.last_status')}>
            <Tag color={statusColor(resultRow?.last_status)}>{statusLabel(resultRow?.last_status)}</Tag>
          </Descriptions.Item>
          <Descriptions.Item label={t('schedule.last_run_at')}>
            {formatDateTimeDisplay(resultRow?.last_run_at)}
          </Descriptions.Item>
          <Descriptions.Item label={t('schedule.last_duration')}>
            {formatDuration(resultRow?.last_duration_ms)}
          </Descriptions.Item>
          {resultRow?.last_error ? (
            <Descriptions.Item label={t('schedule.error')}>
              <pre
                style={{
                  margin: 0,
                  maxHeight: 160,
                  overflow: 'auto',
                  whiteSpace: 'pre-wrap',
                  wordBreak: 'break-word',
                  color: token.colorError,
                }}
              >
                {resultRow.last_error}
              </pre>
            </Descriptions.Item>
          ) : null}
          <Descriptions.Item label={t('schedule.output')}>
            <pre
              style={{
                margin: 0,
                maxHeight: 320,
                overflow: 'auto',
                whiteSpace: 'pre-wrap',
                wordBreak: 'break-word',
                fontSize: 12,
                lineHeight: 1.6,
                fontFamily: "Consolas, 'Courier New', ui-monospace, SFMono-Regular, Menlo, Monaco, monospace",
              }}
            >
              {resultRow?.last_output || t('schedule.output_empty')}
            </pre>
          </Descriptions.Item>
        </Descriptions>
      </Modal>
    </>
  )
}
